// EA Pulse Connectivity Tracker.
// HONEST SCOPE: true seats-per-week data sits behind OAG/Cirium paywalls, so we do NOT
// publish a seat count we cannot verify. Instead we track (a) official airport traffic
// — lagging but authoritative — and (b) confirmed route events, which are forward-looking
// and are what operators can actually act on. Where a monthly seat figure is published
// by a named body (AFRAA), we carry it with that attribution.
window.CONNECT = {
 updated: "22 September 2026 (editor refresh. First full refresh since 25 July. ADDED: AFRAA August 2026 seat capacity (JKIA 567,644, sixth in Africa; Addis 1.25m), UCAA August 2026 Entebbe international passengers (169,706, down 29.1% year on year), KNBS 2025 JKIA annual total (8.93m). ADDED ROUTE EVENTS: Jambojet NBO-EBB (1 Oct), Uganda Airlines EBB-ACC (27 Oct) and EBB-KGL (18 Nov), Ethiopian ADD-JRO-ZNZ to seven weekly (30 Nov), British Airways LGW-JRO-ZNZ (29 May 2027). CORRECTED: the Airlink row previously read 'Johannesburg to Zanzibar / Nairobi, Launching 2026'. That was wrong on both counts. Airlink has flown Johannesburg-Nairobi daily since 24 April 2023, and Johannesburg-Zanzibar launched on 3 June 2026. Carried-over rows not re-checked since 25 July are marked as such.)",
 traffic: [
  { airport:"JKIA Nairobi", code:"NBO", flag:"🇰🇪", metric:"Seat capacity (all carriers)",
    value:"567,644", period:"August 2026", change:"Sixth in Africa; Addis Ababa 1.25m", dir:"flat",
    note:"AFRAA's August ranking. Africa-wide seat capacity rose 8.8% year on year and intra-African seats 10.5%. Nairobi's hub premium over Addis is widening, not narrowing: Addis now offers more than twice JKIA's seats.",
    source:"African Airlines Association (AFRAA), via Capital FM, 16 Sep 2026", verified:true },
  { airport:"JKIA Nairobi", code:"NBO", flag:"🇰🇪", metric:"Passengers handled (annual)",
    value:"8.93m", period:"2025", change:"Kenya commercial airport traffic −1.2% (12.68m vs 12.83m)", dir:"down",
    note:"First national contraction in four years. JKIA runs about 20% above its 7.5m design capacity. A two-day airport workers' strike in early September 2026 disrupted passengers and freight.",
    source:"KNBS Economic Survey 2026, via Streamline Feed 30 May 2026; The EastAfrican 4 Sep 2026", verified:true },
  { airport:"JKIA Nairobi", code:"NBO", flag:"🇰🇪", metric:"Passenger arrivals",
    value:"227,974", period:"March 2026", change:"−0.4% vs February (228,826)", dir:"down",
    note:"Historical row, kept for continuity.",
    source:"KNBS", verified:true },
  { airport:"Entebbe", code:"EBB", flag:"🇺🇬", metric:"International passengers",
    value:"169,706", period:"August 2026", change:"−29.1% year on year", dir:"down",
    note:"The sharpest monthly fall on record for the Uganda shock. Uganda was declared Ebola-free in late August, but the US CDC entry order still covers travellers recently in Uganda (to ~11 Oct 2026). See the Rules tracker.",
    source:"UCAA August 2026 statistics (EA Pulse signal, 20 Sep 2026)", verified:true },
  { airport:"Entebbe", code:"EBB", flag:"🇺🇬", metric:"International arrivals",
    value:"239,850", period:"Q1 2026", change:"−7.9% vs Q1 2025 (260,434)", dir:"down",
    note:"Historical row, kept for continuity.",
    source:"UCAA via Aviation Week", verified:true },
  { airport:"Entebbe", code:"EBB", flag:"🇺🇬", metric:"Terminal capacity",
    value:"3.5m/yr", period:"From Jan 2026", change:"up from 2m", dir:"up",
    note:"New passenger terminal opened January 2026. Capacity is no longer Uganda's constraint; demand is.",
    source:"UCAA", verified:true }
 ],
 routes: [
  { carrier:"Jambojet", route:"Nairobi ⇄ Entebbe", status:"Announced", effective:"1 Oct 2026",
    impact:"Daily, back after six years. One-way fares reported from about US$170. Cheapest scheduled link between the two capitals; useful for Kampala city hotels and UG-KE combination safaris.",
    segment:"City, Bush", source:"allAfrica / Jambojet, 21 Aug 2026", dir:"up" },
  { carrier:"Uganda Airlines", route:"Entebbe ⇄ Accra", status:"Announced", effective:"27 Oct 2026",
    impact:"Four weekly, Boeing 737-800 wet-leased from Ethiopian. First direct West Africa link for Entebbe's hub.",
    segment:"City", source:"ATTA, 5 Aug 2026", dir:"up" },
  { carrier:"Uganda Airlines", route:"Entebbe ⇄ Kigali", status:"Announced", effective:"18 Nov 2026",
    impact:"Daily CRJ-900. Return fares reported from about US$370 against RwandAir's US$450. Makes Bwindi plus Volcanoes a single itinerary without a long drive. Not yet flown a season: keep a fallback routing in 2027 contracts.",
    segment:"Bush, City", source:"ATTA, 5 Aug 2026; EA Pulse Big Read, 19 Sep 2026", dir:"up" },
  { carrier:"Ethiopian Airlines", route:"Addis Ababa ⇄ Kilimanjaro ⇄ Zanzibar", status:"Announced", effective:"30 Nov 2026",
    impact:"Rises from the three weekly originally filed to seven, lifting combined service into JRO and ZNZ to about 21 weekly.",
    segment:"Bush, Beach", source:"EA Pulse Big Read, 19 Sep 2026", dir:"up" },
  { carrier:"British Airways", route:"London Gatwick ⇄ Kilimanjaro ⇄ Zanzibar", status:"Announced", effective:"29 May – 31 Oct 2027",
    impact:"Three weekly (Mon/Thu/Sat). Lands at JRO after dark, so every safari sold off it needs an Arusha or Moshi night before day one.",
    segment:"Bush, Beach", source:"EA Pulse signal, 19 Sep 2026", dir:"up" },
  { carrier:"Airlink (SA)", route:"Johannesburg ⇄ Zanzibar", status:"Operating", effective:"Since 3 Jun 2026",
    impact:"Twice weekly (Wed/Sun ex-JNB, Mon/Thu ex-ZNZ), with an extra weekly flight 15 Dec 2026 – 13 Jan 2027. Southern African feed into the beach market.",
    segment:"Beach", source:"flyairlink.com", dir:"up" },
  { carrier:"Airlink (SA)", route:"Johannesburg ⇄ Nairobi", status:"Operating", effective:"Since 24 Apr 2023",
    impact:"Daily. Not new: an established Southern African feed into Nairobi (this row corrects our earlier 'launching 2026' entry).",
    segment:"City", source:"flyairlink.com", dir:"flat" },
  { carrier:"RwandAir", route:"Kigali ⇄ Zanzibar", status:"Operating", effective:"Bookable on rwandair.com (checked 22 Sep 2026)",
    impact:"Rwanda-Zanzibar gorillas-and-beach combinations without routing through Nairobi or Dar.",
    segment:"Beach, Bush", source:"rwandair.com", dir:"up" },
  { carrier:"Safarilink", route:"Nairobi ⇄ Entebbe (non-stop)", status:"Operating (not re-checked since 25 Jul)", effective:"1 May 2026",
    impact:"Easier multi-country itineraries; good for Kampala city hotels chasing transit corporate traffic.",
    segment:"City", source:"Safarilink / KATA", dir:"up" },
  { carrier:"Safarilink", route:"Nairobi ⇄ Kisumu ⇄ Entebbe", status:"Continues (not re-checked since 25 Jul)", effective:"Since Jan 2026",
    impact:"Twice-daily service retained alongside the non-stop.", segment:"City", source:"KATA", dir:"flat" },
  { carrier:"Uganda Airlines", route:"14 destinations ex-Entebbe", status:"Operating (not re-checked since 25 Jul)", effective:"July 2026 schedule",
    impact:"Daily Nairobi rotations and three weekly to Zanzibar.",
    segment:"City, Beach", source:"KATA", dir:"up" },
  { carrier:"Flightlink (TZ)", route:"Entebbe & Kigali", status:"Announced (not re-checked since 25 Jul)", effective:"2026",
    impact:"Forward signal, not yet flying.",
    segment:"City", source:"Aviation Week", dir:"up" }
 ]
};
