window.LEDGER = {
 "updated": "2026-08-21 12:45",
 "stats": {
  "total": 109,
  "open": 88,
  "resolved": 21,
  "correct": 15,
  "partial": 1,
  "incorrect": 5,
  "accuracy": 74
 },
 "open": [
  {
   "id": "P052",
   "made_date": "2026-08-05",
   "edition": "Morning Brief",
   "claim": "The WHO IHR Emergency Committee meeting on 18 August 2026 will KEEP the Bundibugyo outbreak's PHEIC status and temporary recommendations in force rather than downgrade or terminate them — week-30 acceleration leaves no basis to stand down",
   "resolution_criteria": "A WHO statement after the 18 Aug 2026 IHR EC meeting confirming the PHEIC/temporary recommendations remain in force. If WHO ends or downgrades the PHEIC the call is incorrect",
   "resolve_by": "2026-08-22",
   "market": "Regional",
   "segment": "All",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.who.int/emergencies/disease-outbreak-news/item/2026-DON614",
   "overdue": false
  },
  {
   "id": "P032",
   "made_date": "2026-07-28",
   "edition": "Evening Wrap",
   "claim": "Uganda will record no new confirmed Bundibugyo case before 27 August 2026 and will complete the 42-day countdown — zero active contacts as at 28 July holds",
   "resolution_criteria": "Uganda Ministry of Health EVD dashboard (evd-daily.health.go.ug) or WHO AFRO showing cumulative confirmed cases still at 20 on 27 Aug 2026",
   "resolve_by": "2026-08-28",
   "market": "UG",
   "segment": "Bush/City",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://evd-daily.health.go.ug/",
   "overdue": false
  },
  {
   "id": "P031",
   "made_date": "2026-07-28",
   "edition": "Evening Wrap",
   "claim": "The CDC order expiring 12 August 2026 will be renewed with Uganda still on the designated list — Uganda will NOT be decoupled from DRC before its 42-day all-clear around 27 August 2026",
   "resolution_criteria": "A CDC order or Federal Register notice published between 1 Aug and 27 Aug 2026 continuing the s.362 suspension and naming Uganda among the designated countries",
   "resolve_by": "2026-08-31",
   "market": "Regional",
   "segment": "Bush/City",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.cdc.gov/port-health/legal-authorities/evdorder.html",
   "overdue": false
  },
  {
   "id": "P033",
   "made_date": "2026-07-29",
   "edition": "Morning Brief",
   "claim": "WHO (AFRO or HQ) will publish its own statement acknowledging the end of Uganda's 2026 Bundibugyo outbreak by 31 August 2026",
   "resolution_criteria": "A WHO AFRO news release,Disease Outbreak News item or situation report published between 29 Jul and 31 Aug 2026 stating that Uganda's outbreak has ended or been declared over",
   "resolve_by": "2026-08-31",
   "market": "UG",
   "segment": "Bush/City",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.afro.who.int/countries/uganda/news/uganda-begins-countdown-end-ebola-outbreak",
   "overdue": false
  },
  {
   "id": "P035",
   "made_date": "2026-07-29",
   "edition": "Morning Brief",
   "claim": "The US CDC s.362 entry suspension expiring 12 August 2026 will be renewed or replaced with Uganda REMOVED from the designated country list — the 28 July declaration decouples Uganda from DRC",
   "resolution_criteria": "A CDC order or Federal Register notice published between 1 Aug and 31 Aug 2026 continuing the s.362 suspension WITHOUT naming Uganda among the designated countries",
   "resolve_by": "2026-08-31",
   "market": "Regional",
   "segment": "Bush/City",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.cdc.gov/port-health/legal-authorities/evdorder.html",
   "overdue": false
  },
  {
   "id": "P037",
   "made_date": "2026-07-29",
   "edition": "Midday Pulse (unpublished)",
   "claim": "Kenya's overall US State Department advisory level will remain Level 2 (Exercise Increased Caution) through 31 August 2026 — the 29 July re-issue changed risk indicators and area wording, not the country level",
   "resolution_criteria": "travel.state.gov Kenya travel advisory checked on 31 Aug 2026 still showing 'Kenya - Level 2: Exercise Increased Caution'",
   "resolve_by": "2026-08-31",
   "market": "KE",
   "segment": "City/Bush/Beach",
   "confidence": "Confirmed",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/kenya-travel-advisory.html",
   "overdue": false
  },
  {
   "id": "P096",
   "made_date": "2026-08-17",
   "edition": "pulse-2026-08-17-evening",
   "claim": "The WHO IHR Emergency Committee meeting on 18 August 2026 will MAINTAIN the Bundibugyo PHEIC rather than terminate it — DRC became the deadliest outbreak in its history on 17 Aug with a case fatality ratio of 46% and 55 affected health zones",
   "resolution_criteria": "WHO statement or IHR Emergency Committee communiqué published on or before 31 Aug 2026 confirming the PHEIC remains in force. If WHO terminates the PHEIC at or following the 18 Aug meeting, the call is incorrect",
   "resolve_by": "2026-08-31",
   "market": "Regional",
   "segment": "Bush/City",
   "confidence": "High",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.who.int/groups/ihr-emergency-committee-regarding-the-epidemic-of-ebola-bundibugyo-virus-disease-in-the-drc-and-uganda",
   "overdue": false
  },
  {
   "id": "P085",
   "made_date": "2026-08-16",
   "edition": "pulse-2026-08-16-midday",
   "claim": "Docket CDC-2026-0892 will close its 15-day comment window (opening on Federal Register publication 17 Aug 2026, closing on or about 1 Sep 2026) having received fewer than ten public comments — the East African hospitality trade will again not file",
   "resolution_criteria": "regulations.gov docket CDC-2026-0892 comment count for the August 2026 order, checked after the window closes, is fewer than 10. If ten or more comments are received, incorrect",
   "resolve_by": "2026-09-05",
   "market": "Regional",
   "segment": "Bush/City",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.regulations.gov/docket/CDC-2026-0892",
   "overdue": false
  },
  {
   "id": "P042",
   "made_date": "2026-08-01",
   "edition": "Morning Brief",
   "claim": "Uganda annual headline inflation (UBOS CPI) will print at or above 4.0% in the August 2026 release — i.e. July's utility-driven rise is sustained, not a one-month spike",
   "resolution_criteria": "UBOS August 2026 CPI release (early Sept) shows annual headline inflation >= 4.0%. If below 4.0% the call is incorrect",
   "resolve_by": "2026-09-10",
   "market": "UG",
   "segment": "City/Bush",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.ubos.org/",
   "overdue": false
  },
  {
   "id": "P045",
   "made_date": "2026-08-02",
   "edition": "Morning Brief",
   "claim": "Kenya annual headline inflation (KNBS CPI) will print at or above 6.5% in the August 2026 release (early Sept) — i.e. July's two-year high is sustained, not a one-month fuel and food spike",
   "resolution_criteria": "KNBS August 2026 CPI release (published early Sept) shows annual headline inflation >= 6.5%. If below 6.5% the call is incorrect",
   "resolve_by": "2026-09-10",
   "market": "KE",
   "segment": "City/Bush",
   "confidence": "Confirmed",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.knbs.or.ke/",
   "overdue": false
  },
  {
   "id": "P097",
   "made_date": "2026-08-17",
   "edition": "pulse-2026-08-17-evening",
   "claim": "Uganda completing its 42-day all-clear around 28 August 2026 will NOT be followed within 14 days by any change to US or Canadian entry measures for travellers who have been in Uganda — the stated ground for inclusion is DRC-side overland risk, not Ugandan epidemiology",
   "resolution_criteria": "CDC port-health legal-authorities page and travel.gc.ca health notices checked on 11 Sep 2026. If either the US order or the Canadian quarantine requirement is amended to remove Uganda within 14 days of the all-clear, the call is incorrect",
   "resolve_by": "2026-09-11",
   "market": "Uganda",
   "segment": "Bush/City",
   "confidence": "High",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.cdc.gov/port-health/legal-authorities/evdorder.html",
   "overdue": false
  },
  {
   "id": "P007",
   "made_date": "2026-07-25",
   "edition": "Special Edition",
   "claim": "Rwanda's 30-day DRC entry restriction will remain in force after Uganda's Ebola outbreak is declared over",
   "resolution_criteria": "Rwanda MoH notice still lists the 30-day DRC entry denial 14 days after the WHO/Uganda end-of-outbreak declaration",
   "resolve_by": "2026-09-15",
   "market": "RW",
   "segment": "Bush/City",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P012",
   "made_date": "2026-07-26",
   "edition": "Morning Brief",
   "claim": "Zanzibar's July 2026 arrivals will show year-on-year growth below 10%",
   "resolution_criteria": "Zanzibar Commission for Tourism July 2026 arrivals figure is less than 10% above July 2025's 106,108",
   "resolve_by": "2026-09-15",
   "market": "ZNZ",
   "segment": "Beach",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P029",
   "made_date": "2026-07-28",
   "edition": "Morning Brief",
   "claim": "MV Adan will still be aground off Nyali beach on 1 September 2026 — the mid-August refloating window will slip",
   "resolution_criteria": "Kenya Maritime Authority statement,Kenyan press or KPA notice confirming MV Adan remains aground on or after 1 Sep 2026",
   "resolve_by": "2026-09-15",
   "market": "KE",
   "segment": "Beach",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.standardmedia.co.ke/business/shipping-logistics/article/2001553863/kma-explains-delay-in-salvaging-grounded-ship-off-nyali-beach",
   "overdue": false
  },
  {
   "id": "P051",
   "made_date": "2026-08-04",
   "edition": "Midday Pulse",
   "claim": "Kenya's dengue upsurge keeps climbing — the next WHO AFRO Emergency Preparedness weekly sit-rep after Week 28 reports national cumulative dengue cases above 1,679",
   "resolution_criteria": "A WHO AFRO Emergency Preparedness & Response Weekly Situation Report (Week 29 or later in Aug 2026) showing Kenya cumulative dengue cases above 1,679. If the next available sit-rep shows 1,679 or fewer the call is incorrect",
   "resolve_by": "2026-09-15",
   "market": "KE",
   "segment": "Beach",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.afro.who.int/sites/default/files/2026-07/Week%2028.pdf",
   "overdue": false
  },
  {
   "id": "P074",
   "made_date": "2026-08-13",
   "edition": "pulse-2026-08-13-morning",
   "claim": "Canada's 21-day arrival-quarantine requirement for travellers who have been in Uganda or South Sudan will be extended beyond its stated 29 Aug 2026 expiry — the DRC outbreak trajectory (2,000+ deaths, 4,300+ cases as of 12 Aug) will not have improved enough for Ottawa to let the Quarantine Act measures lapse",
   "resolution_criteria": "Canada.ca Ebola border-measures page or a Public Health Agency of Canada notice checked on 15 Sep 2026 shows the arrival requirements for Uganda/South Sudan still in force beyond 29 Aug 2026. If the measures lapsed on 29 Aug without replacement the call is incorrect",
   "resolve_by": "2026-09-15",
   "market": "Uganda|Regional",
   "segment": "Bush|City",
   "confidence": "medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.canada.ca/en/public-health/services/diseases/ebola/border-measures.html",
   "overdue": false
  },
  {
   "id": "P083",
   "made_date": "2026-08-16",
   "edition": "pulse-2026-08-16-midday",
   "claim": "The US CDC entry order will be continued again at the 11 September 2026 decision point rather than lapse — the DRC contact-tracing rate cited in the 12 Aug order (~78% against a 95% operational threshold) will not have reached 95% by then",
   "resolution_criteria": "CDC legal-authorities page (cdc.gov/port-health/legal-authorities/evdorder.html) or a Federal Register notice on or before 15 Sep 2026 showing a further order continuing the suspension beyond 11 Sep 2026. If the order lapses or is rescinded, incorrect",
   "resolve_by": "2026-09-15",
   "market": "Regional",
   "segment": "Bush/City",
   "confidence": "High",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.cdc.gov/port-health/legal-authorities/evdorder.html",
   "overdue": false
  },
  {
   "id": "P084",
   "made_date": "2026-08-16",
   "edition": "pulse-2026-08-16-midday",
   "claim": "Uganda will still be on the covered-country list at the 11 September 2026 renewal despite completing its 42-day all-clear around 28 August — the stated ground for inclusion is DRC overland cross-border risk, not Ugandan epidemiology",
   "resolution_criteria": "The next CDC order issued on or about 11 Sep 2026 still applies to persons present within DRC, Uganda or South Sudan in the prior 21 days. If Uganda is removed from the covered-country list, incorrect",
   "resolve_by": "2026-09-15",
   "market": "Uganda",
   "segment": "Bush/City",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.cdc.gov/port-health/legal-authorities/evdorder.html",
   "overdue": false
  },
  {
   "id": "P091",
   "made_date": "2026-08-16",
   "edition": "pulse-2026-08-16-evening",
   "claim": "CDC's Travel Health Notices index (wwwnc.cdc.gov/travel/notices) will still carry NO Level 4 Ebola notice on 15 September 2026 while the CDC Ebola situation summary continues to advise avoiding all travel to Ituri and North Kivu — the two surfaces will not be reconciled",
   "resolution_criteria": "Both CDC pages checked on 15 Sep 2026. If the notices index adds a Level 4 Ebola notice, or the situation summary drops its avoid-all-travel advice for Ituri and North Kivu, the surfaces are reconciled and the call is incorrect",
   "resolve_by": "2026-09-15",
   "market": "Regional",
   "segment": "City/Bush",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://wwwnc.cdc.gov/travel/notices",
   "overdue": false
  },
  {
   "id": "P106",
   "made_date": "2026-08-20",
   "edition": "pulse-2026-08-20-morning",
   "claim": "The 19 Aug Samburu helicopter crash (Lady Lori EC130, &Beyond charter, Loisaba–Ewaso Nyiro) will NOT trigger a change in the US or UK travel-advisory LEVEL for Kenya within 30 days — it is an aviation-safety accident under KCAA investigation, not a systemic security or health downgrade",
   "resolution_criteria": "travel.state.gov Kenya advisory and gov.uk/foreign-travel-advice/kenya checked 19 Sep 2026 show the country advisory level unchanged (US Level 2 / UK as at 20 Aug). A level change citing the crash resolves incorrect",
   "resolve_by": "2026-09-19",
   "market": "Kenya",
   "segment": "Bush",
   "confidence": "High",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/kenya-travel-advisory.html",
   "overdue": false
  },
  {
   "id": "P048",
   "made_date": "2026-08-02",
   "edition": "Sunday Foresight",
   "claim": "The Kenya-vs-Tanzania cost gap will widen in the next prints — KNBS August CPI (early Sept) at or above 6.5% while Tanzania NBS July/August headline CPI stays at or below 4.0%",
   "resolution_criteria": "KNBS Aug CPI >= 6.5% AND NBS Tanzania headline CPI <= 4.0% in the releases published by 20 Sept 2026. If either fails the call is incorrect",
   "resolve_by": "2026-09-20",
   "market": "Regional",
   "segment": "All",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.knbs.or.ke/",
   "overdue": false
  },
  {
   "id": "P075",
   "made_date": "2026-08-13",
   "edition": "pulse-2026-08-13-morning",
   "claim": "The CDC's next 30-day Title 42 order (due on or about 10-11 Sep 2026) will STILL name Uganda alongside DRC and South Sudan — Uganda will not be decoupled despite its 28 Jul Ebola-free declaration and the ~28 Aug completion of its 42-day all-clear",
   "resolution_criteria": "CDC port-health order page or Federal Register notice for the order succeeding the 12 Aug 2026 renewal, checked by 20 Sep 2026, still lists Uganda as a covered country. If Uganda is dropped from the order the call is incorrect",
   "resolve_by": "2026-09-20",
   "market": "Uganda",
   "segment": "Bush|City",
   "confidence": "medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.cdc.gov/port-health/legal-authorities/evdorder.html",
   "overdue": false
  },
  {
   "id": "P078",
   "made_date": "2026-08-15",
   "edition": "pulse-2026-08-15-morning",
   "claim": "EPRA's next review effective on/around 15 Sep 2026 will set Nairobi diesel ABOVE KSh217.86/L — the PDL stabilisation kitty is near-depleted and landed petrol costs rose 6.9%, leaving no cushion to repeat the cross-subsidy",
   "resolution_criteria": "EPRA published maximum retail petroleum price schedule effective on/around 15 Sep 2026 shows Nairobi diesel above KSh217.86/L. If at or below, the call is incorrect",
   "resolve_by": "2026-09-20",
   "market": "Kenya",
   "segment": "Bush/Beach/City",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.epra.go.ke/",
   "overdue": false
  },
  {
   "id": "P080",
   "made_date": "2026-08-15",
   "edition": "pulse-2026-08-15-morning",
   "claim": "Kenya's fuel cross-subsidy mechanism will still be in use at the 15 Sep 2026 review — the High Court challenge and MPs' legality objection will not stop it before then",
   "resolution_criteria": "The EPRA notice for the cycle effective ~15 Sep 2026 again holds one grade flat or cross-subsidised, or explicitly cites stabilisation support. If EPRA prices all three grades to landed cost with no stabilisation, the call is incorrect",
   "resolve_by": "2026-09-20",
   "market": "Kenya",
   "segment": "Bush/Beach/City",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.epra.go.ke/",
   "overdue": false
  },
  {
   "id": "P017",
   "made_date": "2026-07-26",
   "edition": "Midday Pulse",
   "claim": "Uganda's 25-27 September park waiver will cover entry fees only — game drives , boat cruises and permits remain chargeable",
   "resolution_criteria": "UWA or Ministry of Tourism published notice confirming scope of the free-entry days as entry fees only",
   "resolve_by": "2026-09-24",
   "market": "UG",
   "segment": "Bush",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P002",
   "made_date": "2026-07-25",
   "edition": "Special Edition",
   "claim": "The US State Department will NOT lower Uganda from Level 4 within 30 days of the outbreak being declared over",
   "resolution_criteria": "State Dept Uganda advisory still Level 4 thirty days after the WHO declaration",
   "resolve_by": "2026-09-26",
   "market": "UG",
   "segment": "Bush/City",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P027",
   "made_date": "2026-07-28",
   "edition": "Morning Brief",
   "claim": "The KAWU aviation strike suspension will hold — no nationwide Kenyan aviation strike or JKIA industrial action will actually commence before 30 September 2026",
   "resolution_criteria": "No reported commencement of a KAWU nationwide strike or JKIA work stoppage in Kenyan press,KAA or KCAA notices between 28 Jul and 30 Sep 2026",
   "resolve_by": "2026-09-30",
   "market": "KE",
   "segment": "All",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.the-star.co.ke/news/2026-07-27-aviation-workers-suspend-strike-pave-way-for-talks",
   "overdue": false
  },
  {
   "id": "P050",
   "made_date": "2026-08-04",
   "edition": "Midday Pulse",
   "claim": "Kenya's overall US State Department travel advisory will remain Level 2 through 30 September 2026 — the 3 Aug dengue health alert is a health notice not an advisory-level trigger",
   "resolution_criteria": "travel.state.gov Kenya advisory checked on 30 Sep 2026 still showing 'Kenya - Level 2: Exercise Increased Caution'",
   "resolve_by": "2026-09-30",
   "market": "KE",
   "segment": "Beach/All",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://ke.usembassy.gov/health-alert-dengue-fever-on-kenyan-coast-and-in-wajir-and-garissa-counties/",
   "overdue": false
  },
  {
   "id": "P059",
   "made_date": "2026-08-09",
   "edition": "Sunday Foresight",
   "claim": "Uganda's US State Department advisory will remain Level 4 (Do Not Travel) through 30 September 2026 despite completing its 42-day Ebola all-clear on/around 28 August — confirming the designation tracks DRC and structural factors not Uganda's own epidemiology",
   "resolution_criteria": "travel.state.gov Uganda advisory checked on 30 Sep 2026 still showing Level 4. If it shows Level 3 or lower the call is incorrect",
   "resolve_by": "2026-09-30",
   "market": "UG",
   "segment": "Bush/City",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/uganda-travel-advisory.html",
   "overdue": false
  },
  {
   "id": "P060",
   "made_date": "2026-08-09",
   "edition": "Sunday Foresight",
   "claim": "The UK FCDO Uganda advisory will NOT carry a blanket 'advise against all travel to Uganda' (only regional/border-area warnings) through 30 September 2026 — Western risk designations diverge and the US Level 4 is an outlier",
   "resolution_criteria": "gov.uk/foreign-travel-advice/uganda checked on 30 Sep 2026 showing no blanket advise-against-all-travel-to-Uganda. If FCDO applies a whole-country advise-against-all-travel the call is incorrect",
   "resolve_by": "2026-09-30",
   "market": "UG",
   "segment": "Bush/City",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.gov.uk/foreign-travel-advice/uganda",
   "overdue": false
  },
  {
   "id": "P071",
   "made_date": "2026-08-12",
   "edition": "pulse-2026-08-12-midday",
   "claim": "The rendered travel.state.gov Kenya advisory will still list the Nairobi neighbourhoods of Eastleigh and Kibera under 'Level 4 - Do Not Travel' on 30 September 2026 — the 28 July 2026 revision is a durable content change, not a transient render",
   "resolution_criteria": "travel.state.gov Kenya advisory page checked on 30 Sep 2026 still showing Eastleigh and Kibera under Level 4 Do Not Travel. If they revert to Reconsider Travel or are dropped, the call is incorrect",
   "resolve_by": "2026-09-30",
   "market": "Kenya",
   "segment": "City",
   "confidence": "high",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P081",
   "made_date": "2026-08-16",
   "edition": "pulse-2026-08-16-morning",
   "claim": "Zanzibar's August 2026 arrivals will exceed August 2025's 105,506 — the July 2026 record (107,801) plus the widening peak-season amplitude implies August sets another monthly high",
   "resolution_criteria": "OCGS / Zanzibar Commission for Tourism monthly arrivals release for August 2026 (typically published mid-September, reported by The Citizen / TanzaniaInvest) shows arrivals above 105,506",
   "resolve_by": "2026-09-30",
   "market": "Tanzania/Zanzibar",
   "segment": "Beach",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.thecitizen.co.tz/tanzania/zanzibar/zanzibar-makes-july-tourism-history-with-record-107-801-arrivals-5557592",
   "overdue": false
  },
  {
   "id": "P082",
   "made_date": "2026-08-16",
   "edition": "pulse-2026-08-16-morning",
   "claim": "Europe's share of Zanzibar's monthly arrivals will be below 60% in the OCGS August 2026 release — continuing the dilution from 61.9% (June) to 56.4% (July) as non-European markets grow faster",
   "resolution_criteria": "OCGS / Zanzibar Commission for Tourism August 2026 arrivals release states European arrivals below 60% of total. If Europe's share returns to 60% or above, incorrect",
   "resolve_by": "2026-09-30",
   "market": "Tanzania/Zanzibar",
   "segment": "Beach",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.thecitizen.co.tz/tanzania/zanzibar/zanzibar-makes-july-tourism-history-with-record-107-801-arrivals-5557592",
   "overdue": false
  },
  {
   "id": "P107",
   "made_date": "2026-08-20",
   "edition": "pulse-2026-08-20-midday",
   "claim": "CDC's Title 42 rerouting order covering Uganda/DRC (docket CDC-2026-0892) will be renewed at or after the 11 Sep 2026 assessment rather than allowed to lapse — DRC transmission is climbing (5,021 cases / 2,378 deaths as at WHO 18 Aug) and the release condition is DRC-side",
   "resolution_criteria": "A CDC order/notice extending or renewing the 42 CFR 71.40 rerouting measure for Uganda/DRC travellers is published on regulations.gov (docket CDC-2026-0892) or the CDC returning-travellers page on or after 11 Sep 2026. If the order lapses without renewal the call is incorrect",
   "resolve_by": "2026-09-30",
   "market": "Regional",
   "segment": "City|Bush",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.who.int/emergencies/disease-outbreak-news/item/2026-DON615",
   "overdue": false
  },
  {
   "id": "P003",
   "made_date": "2026-07-24",
   "edition": "Evening Wrap",
   "claim": "Kenya peak-season arrivals hold up despite political rhetoric discouraging visitors",
   "resolution_criteria": "August 2026 arrivals at or above August 2025 (277,155) per Tourism Research Institute or ministry data",
   "resolve_by": "2026-10-15",
   "market": "KE",
   "segment": "All",
   "confidence": "Confirmed",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P043",
   "made_date": "2026-08-01",
   "edition": "Morning Brief",
   "claim": "RwandAir will still operate 4 weekly Kigali–Paris(CDG)–Brussels rotations as of 15 October 2026 — the winter frequency increase holds rather than being trimmed",
   "resolution_criteria": "RwandAir published timetable/schedule filing checked on 15 Oct 2026 showing 4x weekly Kigali-CDG-Brussels. If reduced to 3x or fewer the call is incorrect",
   "resolve_by": "2026-10-15",
   "market": "RW",
   "segment": "City/Bush",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.rwandair.com/",
   "overdue": false
  },
  {
   "id": "P041",
   "made_date": "2026-07-31",
   "edition": "Morning Brief",
   "claim": "The 2026 Yas Zanzibar International Marathon will be held on 25 October 2026 (not 20 September 2026)",
   "resolution_criteria": "The Citizen TZ or the official Yas/marathon channel confirms a 25 October 2026 race date. If held on 20 Sept or another date the call is incorrect/partial",
   "resolve_by": "2026-10-26",
   "market": "TZ",
   "segment": "Beach/City",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.thecitizen.co.tz/tanzania/sports/zanzibar-marathon-targets-sports-tourism-set-for-october-25-5539466",
   "overdue": false
  },
  {
   "id": "P040",
   "made_date": "2026-07-31",
   "edition": "Morning Brief",
   "claim": "Within 90 days of the 30 July 2026 CEO appointment (by 29 Oct 2026), Rwanda's OPM/RDB or ATL Holding will announce at least one named hotel or commercial investor/tender for Bugesera 'Airport City' — confirming the appointment marks a shift from masterplan to procurement",
   "resolution_criteria": "A search of OPM Rwanda, RDB, ATL Holding and KT Press/New Times between 30 Jul and 29 Oct 2026 returning a named hotel or commercial Airport City tender/investor. If none surfaces the call is incorrect",
   "resolve_by": "2026-10-29",
   "market": "RW",
   "segment": "City/Bush",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://en.webrwanda.com/2026/07/brig-gen-munyengango-appointed-atl-ceo.html",
   "overdue": false
  },
  {
   "id": "P008",
   "made_date": "2026-07-25",
   "edition": "Special Edition",
   "claim": "Entebbe international arrivals fall again year-on-year in Q2 2026 following the Q1 decline of 7.9%",
   "resolution_criteria": "UCAA or Aviation Week Q2 2026 figures below Q2 2025",
   "resolve_by": "2026-10-31",
   "market": "UG",
   "segment": "All",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P009",
   "made_date": "2026-07-25",
   "edition": "Evening Wrap",
   "claim": "No Kenyan court will order a halt to operations at any Maasai Mara reserve camp before the 2026 crossing season ends",
   "resolution_criteria": "No ELC or appellate order suspending operations of Ritz-Carlton Mara , Sala's Camp or Elewana Sand River reported by Business Daily or published on Kenya Law by 31 Oct 2026",
   "resolve_by": "2026-10-31",
   "market": "KE",
   "segment": "Bush",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P011",
   "made_date": "2026-07-26",
   "edition": "Morning Brief",
   "claim": "Tanzania's Fair Competition Commission will clear the A Squared Holding / Nawiri Group transaction without divestiture conditions",
   "resolution_criteria": "FCC issues an unconditional clearance decision on the A Squared / Nawiri merger as reported by the FCC register , TanzaniaInvest or Tanzanian business press",
   "resolve_by": "2026-10-31",
   "market": "TZ",
   "segment": "Bush",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P079",
   "made_date": "2026-08-15",
   "edition": "pulse-2026-08-15-morning",
   "claim": "No hospitality-specific NEW tax, levy or rate increase will appear in the final 2026 BROP submitted to Parliament — Treasury closes the FY2027/28 gap through compliance and base-broadening, not a named tourism/accommodation charge",
   "resolution_criteria": "The final 2026 Budget Review and Outlook Paper (Cabinet ~26 Aug, Parliament thereafter) contains no new or increased tourism, accommodation, catering or tourism-fund levy. If a named hospitality charge appears, the call is incorrect",
   "resolve_by": "2026-10-31",
   "market": "Kenya",
   "segment": "City/Bush/Beach",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.treasury.go.ke/",
   "overdue": false
  },
  {
   "id": "P089",
   "made_date": "2026-08-16",
   "edition": "pulse-2026-08-16-evening",
   "claim": "Africa CDC will NOT terminate the Public Health Emergency of Continental Security (PHECS) for the Bundibugyo outbreak before 31 October 2026 — the ECG recorded ~100 new cases a day and R(t) consistently above 1 on 14 August",
   "resolution_criteria": "Africa CDC statement or press release checked on 31 Oct 2026 shows the PHECS declaration still in force. If Africa CDC formally ends the PHECS on or before 31 Oct 2026 the call is incorrect",
   "resolve_by": "2026-10-31",
   "market": "Regional",
   "segment": "Bush/City",
   "confidence": "High",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://africacdc.org/news-item/africa-cdc-welcomes-emergency-consultative-group-recommendations-on-ebola-bundibugyo-response/",
   "overdue": false
  },
  {
   "id": "P095",
   "made_date": "2026-08-17",
   "edition": "pulse-2026-08-17-midday",
   "claim": "Africa Global PR Week (26–28 Aug 2026, Mövenpick Nairobi) will not produce a measurable city-wide Nairobi rate event — its 1,000+ delegate figure covers online attendance and its physical footprint is a single venue cluster",
   "resolution_criteria": "No Kenyan hospitality trade report, KNBS/TRI data or hotel-group statement published by 31 Oct 2026 attributes a city-wide Nairobi occupancy or ADR spike to AGPRW for 26–28 Aug 2026. A named report attributing city-wide compression to the event resolves incorrect",
   "resolve_by": "2026-10-31",
   "market": "Kenya",
   "segment": "City",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://atta.travel/resource/kenya-tourism-board-named-lead-destination-partner-for-africa-global-pr-week-2026.html",
   "overdue": false
  },
  {
   "id": "P099",
   "made_date": "2026-08-17",
   "edition": "pulse-2026-08-17-evening",
   "claim": "The Miss Tourism East Africa finals (5–12 Sep 2026, Marriott Kampala) will NOT produce a measurable Kampala city-wide rate or occupancy event — roughly two dozen contestants is a single-property booking, not city compression",
   "resolution_criteria": "No Ugandan hospitality trade report, UBOS data or hotel-group statement published by 31 Oct 2026 attributes a city-wide Kampala occupancy or ADR spike to the event. A named report attributing city-wide compression resolves incorrect",
   "resolve_by": "2026-10-31",
   "market": "Uganda",
   "segment": "City",
   "confidence": "High",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://allafrica.com/stories/202608170290.html",
   "overdue": false
  },
  {
   "id": "P064",
   "made_date": "2026-08-10",
   "edition": "Evening Wrap",
   "claim": "Kenya's EPRA super petrol price (Nairobi) in the review effective on/around 15 November 2026 will print ABOVE KSh 214.03/L — the 8% fuel-VAT concession (extended only to 14 Oct 2026) lapses and removes the prop holding today's flat price",
   "resolution_criteria": "The EPRA monthly fuel price review effective on/around 15 Nov 2026 shows Nairobi super petrol above KSh 214.03/L. If at or below KSh 214.03/L the call is incorrect",
   "resolve_by": "2026-11-20",
   "market": "KE",
   "segment": "All",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.epra.go.ke/",
   "overdue": false
  },
  {
   "id": "P026",
   "made_date": "2026-07-27",
   "edition": "Midday Pulse",
   "claim": "Exercise Haraka Storm will be conducted in Tanzania rather than Kenya during September-November 2026",
   "resolution_criteria": "UK MoD,British Army or reputable press reporting Exercise Haraka Storm held in Tanzania between 1 Sep and 30 Nov 2026",
   "resolve_by": "2026-12-15",
   "market": "KE",
   "segment": "Bush",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.standardmedia.co.ke/national/article/2001553563/why-uk-moved-batuk-training-to-tanzania",
   "overdue": false
  },
  {
   "id": "P015",
   "made_date": "2026-07-26",
   "edition": "Midday Pulse",
   "claim": "At least one further Kenyan hotel of 100+ rooms will be placed under administration or receivership by a lender before 31 Dec 2026",
   "resolution_criteria": "A gazetted Insolvency Act notice or Business Daily , Khusoko report of a 100+ room Kenyan hotel entering administration or receivership between 27 Jul and 31 Dec 2026",
   "resolve_by": "2026-12-31",
   "market": "KE",
   "segment": "City/Beach",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P022",
   "made_date": "2026-07-27",
   "edition": "Morning Brief",
   "claim": "No Bundibugyo vaccine will be licensed or deployed for outbreak use in DRC or Uganda before 31 December 2026 — the DRC Prime Minister's \"two to four months\" timeline will not hold",
   "resolution_criteria": "No WHO prequalification,emergency use listing or national regulatory approval of a Bundibugyo-specific vaccine and no ring or mass vaccination campaign reported by WHO,Africa CDC or Oxford Vaccine Group by 31 Dec 2026",
   "resolve_by": "2026-12-31",
   "market": "Regional",
   "segment": "All",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.ox.ac.uk/news/2026-07-24-first-volunteer-vaccinated-in-the-worlds-first-bundibugyo-ebolavirus-vaccine-trial",
   "overdue": false
  },
  {
   "id": "P024",
   "made_date": "2026-07-27",
   "edition": "Midday Pulse",
   "claim": "Kenya will not renew BATUK's training licences before 31 December 2026",
   "resolution_criteria": "UK MoD,British High Commission Nairobi or Kenyan Ministry of Defence announcement confirming renewal of BATUK training licences published by 31 Dec 2026",
   "resolve_by": "2026-12-31",
   "market": "KE",
   "segment": "Bush/City",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.standardmedia.co.ke/rift-valley/article/2001553819/shadow-of-impunity-how-years-of-alleged-atrocities-finally-led-to-batuks-departure-from-kenya",
   "overdue": false
  },
  {
   "id": "P049",
   "made_date": "2026-08-02",
   "edition": "Sunday Foresight",
   "claim": "No East African national tourism authority (Kenya,Tanzania,Uganda,Rwanda) will announce a headline national-park or gorilla-permit fee CUT to close the price gap with South Africa before 31 December 2026",
   "resolution_criteria": "No KWS,TANAPA,UWA,RDB or ministry notice cutting a headline park/permit fee published by 31 Dec 2026. A fee rise or freeze does not count; only a cut resolves it correct-if-none",
   "resolve_by": "2026-12-31",
   "market": "Regional",
   "segment": "Bush",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://rdb.rw/",
   "overdue": false
  },
  {
   "id": "P054",
   "made_date": "2026-08-05",
   "edition": "Evening Wrap",
   "claim": "Uganda Airlines will operate the daily Entebbe–Kigali service by 31 December 2026 — the 18 Nov launch holds rather than slipping",
   "resolution_criteria": "ch-aviation,Uganda Airlines timetable or Ugandan press confirms a daily Entebbe-Kigali service operating on or before 31 Dec 2026. If not launched by then the call is incorrect",
   "resolve_by": "2026-12-31",
   "market": "UG",
   "segment": "City",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.newvision.co.ug/category/business/uganda-airlines-opens-new-routes-to-accra-kig-NV_238262_082026",
   "overdue": false
  },
  {
   "id": "P066",
   "made_date": "2026-08-11",
   "edition": "Midday Pulse",
   "claim": "Kenya's gazetted US$50,000 mandatory travel-health insurance will NOT be operational (enforced at ports of entry) before 31 Dec 2026",
   "resolution_criteria": "No official notice or reported enforcement of the US$50k travel-insurance requirement at Kenyan entry points by 31 Dec 2026, given the 29 Sep 2026 High Court challenge",
   "resolve_by": "2026-12-31",
   "market": "KE",
   "segment": "All",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.tourismupdate.com/article/trade-questions-kenya-insurance-mandate",
   "overdue": false
  },
  {
   "id": "P068",
   "made_date": "2026-08-11",
   "edition": "Midday Pulse",
   "claim": "Kampala's full Marriott-brand flagship (Nsambya) will open to the public before 31 Dec 2026",
   "resolution_criteria": "Marriott.com or the operator confirms the Kampala Marriott Hotel is open and bookable for stays by 31 Dec 2026",
   "resolve_by": "2026-12-31",
   "market": "UG",
   "segment": "City",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.marriott.com/en-us/hotels/ebbmk-kampala-marriott-hotel/overview/",
   "overdue": false
  },
  {
   "id": "P070",
   "made_date": "2026-08-11",
   "edition": "Evening Wrap",
   "claim": "Uganda Airlines will launch Entebbe-Accra on/around 27 Oct 2026 and Entebbe-Kigali on/around 18 Nov 2026 as announced",
   "resolution_criteria": "ch-aviation/AeroRoutes/the airline or Ugandan press confirm both routes operating within 30 days of the stated dates (Accra 27 Oct and Kigali 18 Nov)",
   "resolve_by": "2026-12-31",
   "market": "UG",
   "segment": "City",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.theeastafrican.co.ke/tea/business-tech/uganda-airlines-adds-kigali-accra-to-route-network-5547894",
   "overdue": false
  },
  {
   "id": "P073",
   "made_date": "2026-08-12",
   "edition": "pulse-2026-08-12-midday",
   "claim": "TUI's FY2026 results (due ~Dec 2026) will report full-year underlying EBIT within or above the guidance range confirmed at Q3 on 12 August 2026 — the four-week +7% booking uplift signals a late curve, not a demand collapse",
   "resolution_criteria": "TUI Group FY2026 results release checked on publication showing underlying EBIT at or above the FY26 guidance confirmed on 12 Aug 2026. A further guidance cut or a miss makes the call incorrect",
   "resolve_by": "2026-12-31",
   "market": "Global|Zanzibar|Kenya coast",
   "segment": "Beach",
   "confidence": "medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P076",
   "made_date": "2026-08-13",
   "edition": "pulse-2026-08-13-midday",
   "claim": "The Lux Collective's Phase 1 Rwanda rebrands — LUX* Lake Kivu (ex-Cleo Lake Kivu) and SALT of Akagera (ex-Akagera Game Lodge) — will be live and bookable under their new brands by 31 Dec 2026, per the mid-2026 phase-one timeline announced 31 Jul 2026",
   "resolution_criteria": "The Lux Collective site (theluxcollective.com) or a booking channel lists LUX* Lake Kivu and/or SALT of Akagera as open and bookable by 31 Dec 2026. If neither is bookable under the new brand the call is incorrect",
   "resolve_by": "2026-12-31",
   "market": "RW",
   "segment": "Bush",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.hospitalitynet.org/news/4132774/the-lux-collective-enters-rwanda-with-landmark-ultra-luxury-tourism-circuit-partnership",
   "overdue": false
  },
  {
   "id": "P103",
   "made_date": "2026-08-18",
   "edition": "pulse-2026-08-18-special",
   "claim": "Mombasa (MIA) arrivals will keep outpacing JKIA on YoY growth in the next KNBS arrivals print (May–June 2026) — the coast is recovering faster than the Nairobi gateway, not a one-quarter artefact",
   "resolution_criteria": "The next KNBS Leading Economic Indicators covering May–June 2026 shows MIA year-on-year arrivals growth exceeding JKIA year-on-year growth. If JKIA growth matches or exceeds MIA, the call is incorrect",
   "resolve_by": "2026-12-31",
   "market": "Kenya",
   "segment": "City/Beach",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.knbs.or.ke/",
   "overdue": false
  },
  {
   "id": "P105",
   "made_date": "2026-08-19",
   "edition": "pulse-2026-08-19-evening",
   "claim": "Uganda's US State Department travel advisory will NOT drop below Level 4 before 31 December 2026 — the Level 4 is pinned to the DRC Bundibugyo epidemic (still growing, ~5,000 cases) rather than Ugandan epidemiology (Uganda declared its own outbreak over on 28 Jul 2026), and advisories lag outbreaks",
   "resolution_criteria": "travel.state.gov Uganda advisory page checked 31 Dec 2026 shows Level 4 (Do Not Travel) still in force. A drop to Level 3 or below before 31 Dec 2026 resolves incorrect",
   "resolve_by": "2026-12-31",
   "market": "Uganda",
   "segment": "City|Bush",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/uganda-travel-advisory.html",
   "overdue": false
  },
  {
   "id": "P006",
   "made_date": "2026-07-25",
   "edition": "Morning Brief",
   "claim": "Regional airlift into East Africa continues expanding faster than rate discipline can absorb",
   "resolution_criteria": "Net seat capacity into NBO/EBB/ZNZ/KGL up year-on-year while published lead-in rates flat or down",
   "resolve_by": "2027-01-31",
   "market": "Regional",
   "segment": "All",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P010",
   "made_date": "2026-07-25",
   "edition": "Evening Wrap",
   "claim": "Uganda's 10-year tourism tax holiday will not produce a publicly announced branded hotel signing of US$10m or more before FHS Africa Kampala",
   "resolution_criteria": "No Uganda hotel investment of US$10m+ announced by Uganda Investment Authority , UTB or hospitality trade press between 25 Jul 2026 and 3 Feb 2027",
   "resolve_by": "2027-02-03",
   "market": "UG",
   "segment": "City/Bush",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P055",
   "made_date": "2026-08-05",
   "edition": "Evening Wrap",
   "claim": "RwandAir will not cut its Entebbe–Kigali frequency in response to Uganda Airlines' entry within 90 days of the 18 Nov 2026 launch — it defends the corridor rather than ceding it",
   "resolution_criteria": "RwandAir published timetable or ch-aviation checked ~16 Feb 2027 shows Entebbe-Kigali frequency at or above its pre-18-Nov-2026 level. If RwandAir reduces frequency the call is incorrect",
   "resolve_by": "2027-02-16",
   "market": "RW",
   "segment": "City",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.rwandair.com/",
   "overdue": false
  },
  {
   "id": "P004",
   "made_date": "2026-07-24",
   "edition": "Morning Brief",
   "claim": "Nairobi hotel occupancy or ADR comes under measurable pressure as ~1,500 branded rooms open in 2026",
   "resolution_criteria": "Published Nairobi occupancy or ADR for H2 2026 below the equivalent 2025 period",
   "resolve_by": "2027-03-31",
   "market": "KE",
   "segment": "City",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P014",
   "made_date": "2026-07-26",
   "edition": "Midday Pulse",
   "claim": "Glee Hotel will change hands via the administrator rather than return to Mary Wambui Mungai's control",
   "resolution_criteria": "Administrator's report or Business Daily , Khusoko reporting a completed sale , transfer or new owner of Glee Hotel Limited by 31 Mar 2027",
   "resolve_by": "2027-03-31",
   "market": "KE",
   "segment": "City",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P063",
   "made_date": "2026-08-10",
   "edition": "Midday Pulse",
   "claim": "Kenya's domestic air travel will keep outpacing international — the next KAA/KNBS air-passenger data covering a period beyond June 2026 shows domestic routes at or above 40% of total traffic, confirming the domestic share is structural not a one-off school-holiday spike",
   "resolution_criteria": "KAA preliminary data or KNBS Leading Economic Indicators covering a period after June 2026 (published by 31 Mar 2027) shows domestic passengers >= 40% of total air traffic. If domestic share prints below 40% the call is incorrect",
   "resolve_by": "2027-03-31",
   "market": "KE",
   "segment": "All",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.kcaa.or.ke/about-us/statistics/passenger-traffic",
   "overdue": false
  },
  {
   "id": "P069",
   "made_date": "2026-08-11",
   "edition": "Evening Wrap",
   "claim": "KWS/PCPB confirmatory toxicology will attribute the June-July Amboseli elephant deaths mainly to agrochemical/pesticide (cyanide) poisoning rather than organised poaching for ivory",
   "resolution_criteria": "KWS or Pest Control Products Board final report or Kenyan national press citing it attributes the Amboseli-Kimana elephant deaths primarily to pesticide/agrochemical (cyanide) poisoning rather than ivory poaching by 31 Mar 2027",
   "resolve_by": "2027-03-31",
   "market": "KE",
   "segment": "Bush",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://peopledaily.digital/inside-politics/kws-toxicology-reports-find-16-elephants-in-amboseli-died-from-cyanide-poisoning",
   "overdue": false
  },
  {
   "id": "P087",
   "made_date": "2026-08-16",
   "edition": "Sunday Foresight",
   "claim": "No major European tour operator will announce a REDUCTION in committed Zanzibar capacity for Winter 2026/27 or Winter 2027/28 before 31 March 2027 — the channel is softening in aggregate volume, not retreating from this destination",
   "resolution_criteria": "No announcement by TUI, DER Touristik, Neckermann, Alpitour or comparable European operator of reduced Zanzibar flight or hotel capacity for W26/27 or W27/28, per company newsroom or trade press (TTG, Travel Weekly, Tourism Update), checked 31 Mar 2027. Any announced cut resolves incorrect",
   "resolve_by": "2027-03-31",
   "market": "ZNZ",
   "segment": "Beach",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P088",
   "made_date": "2026-08-16",
   "edition": "Sunday Foresight",
   "claim": "Airlink's Cape Town-Zanzibar Saturday service will still be operating at one or more weekly rotations on 31 March 2027 — regional airlift into Zanzibar sticks rather than proving a seasonal trial",
   "resolution_criteria": "ch-aviation, AeroRoutes or Airlink's published timetable checked on 31 Mar 2027 shows a Cape Town-Zanzibar service operating at 1x weekly or more. If suspended or withdrawn the call is incorrect",
   "resolve_by": "2027-03-31",
   "market": "ZNZ",
   "segment": "Beach",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P090",
   "made_date": "2026-08-16",
   "edition": "pulse-2026-08-16-evening",
   "claim": "Ervebo will NOT receive a WHO or Africa CDC recommendation for routine non-trial mass use against Bundibugyo virus by 31 March 2027 — the ECG found no reliable evidence of clinical efficacy and confined use to trial and compassionate protocols",
   "resolution_criteria": "WHO SAGE, WHO Ebola guidance or an Africa CDC statement published by 31 Mar 2027 recommending Ervebo for routine (non-trial, non-compassionate) use against Bundibugyo virus. If such a recommendation is issued the call is incorrect",
   "resolve_by": "2027-03-31",
   "market": "Regional",
   "segment": "Bush/City",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://africacdc.org/news-item/africa-cdc-welcomes-emergency-consultative-group-recommendations-on-ebola-bundibugyo-response/",
   "overdue": false
  },
  {
   "id": "P093",
   "made_date": "2026-08-17",
   "edition": "pulse-2026-08-17-midday",
   "claim": "TRA will not publicly announce a contract award for the Fumba Port cargo scanner before 31 March 2027 — the 15 Aug 2026 statement was a pledge with no budget, tender reference or installation date attached",
   "resolution_criteria": "A TRA, Tanzania National e-Procurement System (NeST) or Zanzibar government notice, or reputable press report, naming an awarded supplier or contract value for a Fumba Port scanner, published on or before 31 Mar 2027. If such an award is announced, the call is incorrect",
   "resolve_by": "2027-03-31",
   "market": "Tanzania/Zanzibar",
   "segment": "Beach",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.thecitizen.co.tz/tanzania/business/fumba-port-set-to-boost-zanzibar-trade-and-revenue-as-tra-plans-modern-cargo-scanner-5560562",
   "overdue": false
  },
  {
   "id": "P100",
   "made_date": "2026-08-18",
   "edition": "pulse-2026-08-18-morning",
   "claim": "Uganda Airlines' Entebbe–Accra service (4x weekly, launching 27 Oct 2026) will still operate at 3x weekly or more on 31 March 2027 — a test of whether thin-margin new African routes survive their first season",
   "resolution_criteria": "ch-aviation, AeroRoutes or Uganda Airlines' published timetable checked on 31 Mar 2027 shows Entebbe–Accra at 3x weekly or more. If suspended or reduced below 3x weekly the call is incorrect",
   "resolve_by": "2027-03-31",
   "market": "Regional",
   "segment": "City/Bush",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.theeastafrican.co.ke/tea/business-tech/uganda-airlines-adds-kigali-accra-to-route-network-5547894",
   "overdue": false
  },
  {
   "id": "P104",
   "made_date": "2026-08-19",
   "edition": "pulse-2026-08-19-morning",
   "claim": "Kenya's full-year 2026 arrivals from Uganda will exceed the 2025 figure of 234,556 — regional source-market growth continues rather than stalling",
   "resolution_criteria": "KTB or Tourism Research Institute 2026 annual/leading-indicator report shows Uganda arrivals to Kenya above 234,556 for calendar 2026",
   "resolve_by": "2027-03-31",
   "market": "KE",
   "segment": "City|Bush|Beach",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P019",
   "made_date": "2026-07-26",
   "edition": "Sunday Foresight",
   "claim": "Rwanda's DRC arrivals will fall year-on-year in H2 2026 as the 30-day entry restriction bites",
   "resolution_criteria": "RDB or NISR H2 2026 / full-year 2026 arrivals data showing DRC arrivals below the H2 2025 equivalent",
   "resolve_by": "2027-04-30",
   "market": "RW",
   "segment": "City/Bush",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P061",
   "made_date": "2026-08-09",
   "edition": "Evening Wrap",
   "claim": "The 2027 W Hospitality Group Hotel Chain Development Pipelines in Africa report will show East Africa (Kenya,Ethiopia,Tanzania) retaining the highest rooms-under-construction ratio of any African sub-region — i.e. the 2026 construction concentration persists rather than reverting to a signings-only pipeline",
   "resolution_criteria": "The 2027 edition of the W Hospitality Group Africa pipeline report (published by 30 Apr 2027) shows Kenya,Ethiopia and Tanzania among the leading African markets by rooms-under-construction ratio (each above 60%). If East Africa's under-construction lead disappears the call is incorrect",
   "resolve_by": "2027-04-30",
   "market": "Regional",
   "segment": "City",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://w-hospitalitygroup.com/pipeline-report/",
   "overdue": false
  },
  {
   "id": "P013",
   "made_date": "2026-07-26",
   "edition": "Morning Brief",
   "claim": "Rwanda's MICE revenue will exceed US$100m for the first time in calendar 2026",
   "resolution_criteria": "RDB 2026 Annual Report reports MICE revenue above US$100 million",
   "resolve_by": "2027-05-31",
   "market": "RW",
   "segment": "City",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P108",
   "made_date": "2026-08-21",
   "edition": "pulse-2026-08-21-morning",
   "claim": "African/regional source markets will supply a larger share of Rwanda full-year 2026 arrivals than in 2025 — intra-African demand (DRC led at 12.5% in H1) outgrows long-haul",
   "resolution_criteria": "RDB or NISR full-year 2026 tourism data shows the combined African-market share of Rwanda arrivals above the 2025 share",
   "resolve_by": "2027-05-31",
   "market": "RW",
   "segment": "City|Bush",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.statistics.gov.rw/",
   "overdue": false
  },
  {
   "id": "P005",
   "made_date": "2026-07-24",
   "edition": "Midday Pulse",
   "claim": "Zanzibar branded all-inclusive supply growth pressures independent resort rate benchmarks",
   "resolution_criteria": "Evidence of independent Zanzibar resorts cutting published rates or reporting allocation loss into 2027",
   "resolve_by": "2027-06-30",
   "market": "ZNZ",
   "segment": "Beach",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P065",
   "made_date": "2026-08-11",
   "edition": "Morning Brief",
   "claim": "At least one recently launched or resumed intra-African/regional passenger route serving an East African gateway (NBO,EBB,ZNZ,KGL,MBA) will be suspended or cut in frequency before 30 Jun 2027 as carriers manage sub-1% net margins",
   "resolution_criteria": "ch-aviation,AeroRoutes,airline notice or regional press reporting the suspension or a frequency reduction of a route launched or resumed since Jan 2025 into NBO,EBB,ZNZ,KGL,MBA, dated before 30 Jun 2027",
   "resolve_by": "2027-06-30",
   "market": "Regional",
   "segment": "All",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.iata.org/en/pressroom/2025-releases/2025-12-09-01/",
   "overdue": false
  },
  {
   "id": "P067",
   "made_date": "2026-08-11",
   "edition": "Midday Pulse",
   "claim": "Tanzania will withhold or refuse at least one hospitality business-licence renewal for lack of a compliant digital-payment facility before 30 Jun 2027",
   "resolution_criteria": "Reported enforcement, a refused/withheld renewal case, or official confirmation of enforcement of the Electronic Transactions Act digital-payment licence rule by 30 Jun 2027",
   "resolve_by": "2027-06-30",
   "market": "TZ",
   "segment": "All",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.thecitizen.co.tz/tanzania/news/national/tanzania-makes-digital-payments-mandatory-in-key-sectors-5492872",
   "overdue": false
  },
  {
   "id": "P077",
   "made_date": "2026-08-13",
   "edition": "pulse-2026-08-13-midday",
   "claim": "Rwanda's realised 2026 MICE revenue will fall SHORT of the RDB's US$156m target — the binding constraint is intra-African airlift and delegate lift, not conference-space or ambition",
   "resolution_criteria": "RDB or NISR full-year 2026 MICE revenue figure (published by 30 Jun 2027) prints below US$156m. If realised 2026 MICE revenue is at or above US$156m the call is incorrect",
   "resolve_by": "2027-06-30",
   "market": "RW",
   "segment": "City",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.travelandtourworld.com/news/article/from-kigali-to-cape-town-how-rwanda-plans-to-double-mice-earnings-to-two-hundred-and-twenty-four-million-usd-by-2028-and-become-africas-business-tourism-hub/",
   "overdue": false
  },
  {
   "id": "P086",
   "made_date": "2026-08-16",
   "edition": "Sunday Foresight",
   "claim": "Europe's share of Zanzibar arrivals for full-year 2026 will print BELOW its full-year 2025 share — July's fall from 61.9% to 56.4% is structural dilution, not a one-month artefact",
   "resolution_criteria": "OCGS / Zanzibar Commission for Tourism full-year 2026 arrivals data (published by 30 Jun 2027) shows European arrivals as a lower share of total than in full-year 2025. If the share is equal or higher the call is incorrect",
   "resolve_by": "2027-06-30",
   "market": "ZNZ",
   "segment": "Beach",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P094",
   "made_date": "2026-08-17",
   "edition": "pulse-2026-08-17-midday",
   "claim": "Tanzania will not implement nationwide scheduled electricity rationing between the 22 Aug 2026 JNHPP inauguration and 30 June 2027 — with 2,115 MW commissioned and a reported 2,636 MW surplus, generation is no longer the binding constraint on the mainland grid",
   "resolution_criteria": "No TANESCO or Ministry of Energy announcement of nationwide scheduled load-shedding or power rationing between 22 Aug 2026 and 30 Jun 2027, per TANESCO notices and Tanzanian press. Localised outages from transmission or distribution faults do not count; a announced national rationing programme resolves incorrect",
   "resolve_by": "2027-06-30",
   "market": "Tanzania",
   "segment": "City/Bush/Beach",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.thecitizen.co.tz/tanzania/news/national/samia-to-inaugurate-sh7-45-trillion-julius-nyerere-hydropower-project-on-august-22-5559650",
   "overdue": false
  },
  {
   "id": "P098",
   "made_date": "2026-08-17",
   "edition": "pulse-2026-08-17-evening",
   "claim": "The EAC Competition Authority will clear the Volkswagen / Europcar Mobility Group transaction (Merger Inquiry Notice No. 14 of 2026) without structural conditions affecting East African car-rental operations, by 30 June 2027",
   "resolution_criteria": "EAC Competition Authority determination published at eacompetition.org by 30 Jun 2027 showing unconditional clearance or clearance with behavioural conditions only. Any structural remedy (divestiture or franchise separation) touching EAC car-rental operations resolves incorrect",
   "resolve_by": "2027-06-30",
   "market": "Regional",
   "segment": "City/Bush/Beach",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.eacompetition.org/",
   "overdue": false
  },
  {
   "id": "P101",
   "made_date": "2026-08-18",
   "edition": "pulse-2026-08-18-morning",
   "claim": "IATA will NOT revise African airlines' 2026 net profit back above US$200m in its next full-year outlook — the June 2026 downgrade to ~US$100m (US$0.40/passenger) reflects structural cost pressure not a transient shock",
   "resolution_criteria": "IATA December 2026 Global Outlook for Air Transport (or 2026 actuals published by 30 Jun 2027) reports African airlines' 2026 net profit at or below US$200m. If IATA reports 2026 African net profit above US$200m the call is incorrect",
   "resolve_by": "2027-06-30",
   "market": "Regional",
   "segment": "City/Bush/Beach",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.iata.org/en/pressroom/2025-releases/2025-12-09-01/",
   "overdue": false
  },
  {
   "id": "P102",
   "made_date": "2026-08-18",
   "edition": "pulse-2026-08-18-special",
   "claim": "Kenya's full-year 2026 visitor arrivals will exceed full-year 2025 — the Jan–Apr 2026 run-rate of +9.5% YoY (828,830 vs 757,245) will carry through the year",
   "resolution_criteria": "KNBS Leading Economic Indicators or Tourism Research Institute full-year 2026 arrivals (published by 30 Jun 2027) show a total above the 2025 full-year figure. If 2026 arrivals come in at or below 2025, the call is incorrect",
   "resolve_by": "2027-06-30",
   "market": "Kenya",
   "segment": "City/Bush/Beach",
   "confidence": "Medium",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.knbs.or.ke/",
   "overdue": false
  },
  {
   "id": "P016",
   "made_date": "2026-07-26",
   "edition": "Midday Pulse",
   "claim": "Kenya will not cut or remove the airport passenger levy on air tickets before 31 Dec 2027",
   "resolution_criteria": "No Finance Act , gazette notice or KCAA/KAA announcement reducing or abolishing the airport passenger service levy published by 31 Dec 2027",
   "resolve_by": "2027-12-31",
   "market": "KE",
   "segment": "All",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P020",
   "made_date": "2026-07-26",
   "edition": "Sunday Foresight",
   "claim": "Uganda Airlines' Boeing 737-8 MAX and 787-9 order will not deliver a first aircraft before 31 December 2027",
   "resolution_criteria": "No Uganda Airlines 737-8 or 787-9 delivery reported by the airline,Boeing,ch-aviation or Ugandan press by 31 Dec 2027",
   "resolve_by": "2027-12-31",
   "market": "UG",
   "segment": "City",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.newvision.co.ug/category/business/uganda-airlines-orders-eight-boeing-jets-to-e-NV_237451_072026",
   "overdue": false
  },
  {
   "id": "P092",
   "made_date": "2026-08-17",
   "edition": "pulse-2026-08-17-midday",
   "claim": "Fumba Port (Zanzibar) will not be handling 250,000 containers per month by 31 December 2027 — the stated rate of ~40 containers per hour implies a practical ceiling near 28,800 per month, so the 250,000–400,000 monthly figure quoted by ZPC on 15 Aug 2026 will not be met",
   "resolution_criteria": "Zanzibar Ports Corporation, TRA or Zanzibar official statistics published by 31 Dec 2027 show Fumba Port monthly container throughput below 250,000. If throughput reaches or exceeds 250,000 in any month to that date, the call is incorrect",
   "resolve_by": "2027-12-31",
   "market": "Tanzania/Zanzibar",
   "segment": "Beach",
   "confidence": "High",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.thecitizen.co.tz/tanzania/business/fumba-port-set-to-boost-zanzibar-trade-and-revenue-as-tra-plans-modern-cargo-scanner-5560562",
   "overdue": false
  }
 ],
 "resolved": [
  {
   "id": "P072",
   "made_date": "2026-08-12",
   "edition": "pulse-2026-08-12-midday",
   "claim": "No confirmed Ebola (Bundibugyo) case will be recorded outside Africa by 19 August 2026 — the Israeli traveller under test on 11 Aug will not be confirmed positive",
   "resolution_criteria": "Israeli Ministry of Health, WHO Disease Outbreak News or ECDC checked on 19 Aug 2026 showing no confirmed Bundibugyo case outside Africa. Any confirmed export makes the call incorrect",
   "resolve_by": "2026-08-19",
   "market": "Regional",
   "segment": "City|Bush|Beach",
   "confidence": "medium",
   "status": "correct",
   "resolved_date": "2026-08-19",
   "evidence": "Both Israeli suspected Bundibugyo cases (returnees from DRC) tested NEGATIVE and the suspicion was ruled out, no confirmed Bundibugyo export attributable to the flagged traveller as of 19 Aug 2026 (ECDC/WHO/Israel MoH). Earlier US (May) and France (24 Jun) imports predate the 12 Aug claim and its Israeli-traveller framing.",
   "source_url": "https://www.timesofisrael.com/ebola-suspicion-ruled-out-as-expert-says-very-low-chance-current-strain-will-reach-israel/",
   "overdue": false
  },
  {
   "id": "P023",
   "made_date": "2026-07-27",
   "edition": "Morning Brief",
   "claim": "The US CDC will renew its DRC/Uganda/South Sudan Ebola entry restrictions again at the mid-August decision point rather than let them lapse",
   "resolution_criteria": "CDC returning-traveller guidance or Federal Register notice showing the entry restriction order extended beyond 12 August 2026",
   "resolve_by": "2026-08-25",
   "market": "Regional",
   "segment": "All",
   "confidence": "Reported",
   "status": "correct",
   "resolved_date": "2026-08-16",
   "evidence": "CDC renewed the order on 12 Aug 2026 continuing the suspension without change for 30 days, through 4:59pm EDT Friday 11 Sep 2026. Full text on Federal Register public inspection 14 Aug, publication date 17 Aug 2026 (FR Doc 2026-16706, docket CDC-2026-0892). Did not lapse.",
   "source_url": "https://public-inspection.federalregister.gov/2026-16706.pdf",
   "overdue": false
  },
  {
   "id": "P044",
   "made_date": "2026-08-01",
   "edition": "Evening Wrap",
   "claim": "The US CDC Section 362 entry suspension covering DRC, Uganda and South Sudan will be EXTENDED beyond 12 August 2026 rather than lifted — DRC's uncontrolled transmission (contact tracing 78.3%) keeps the regional ban in place at its next renewal",
   "resolution_criteria": "The US CDC port-health order/Federal Register checked on or around 13 Aug 2026 shows the suspension renewed with an end date after 12 Aug 2026. If the order lapses or all three countries are dropped on or before 12 Aug the call is incorrect",
   "resolve_by": "2026-08-13",
   "market": "Regional",
   "segment": "City/Bush",
   "confidence": "Reported",
   "status": "correct",
   "resolved_date": "2026-08-16",
   "evidence": "Federal Register: 'Order Under Sections 362 and 365 of the PHS Act Continuing the Suspension of the Right To Introduce Certain Persons...' (doc 2026-16706, FR dated 17 Aug 2026) continues the 30-day suspension covering DRC, Uganda and South Sudan. Prior continuations 21 Jun and 13 Jul 2026. Order renewed rather than lifted, DRC still listed.",
   "source_url": "https://www.federalregister.gov/documents/2026/08/17/2026-16706/order-under-sections-362-and-365-of-the-public-health-service-act-continuing-the-suspension-of-the",
   "overdue": false
  },
  {
   "id": "P047",
   "made_date": "2026-08-02",
   "edition": "Sunday Foresight",
   "claim": "The US CDC Section 362 Ebola entry suspension covering DRC/Uganda/South Sudan will be renewed on or around 12 August 2026 with DRC still listed — the 3,605-case 44% CFR outbreak leaves no basis to lift",
   "resolution_criteria": "CDC port-health order/Federal Register checked ~14 Aug 2026 shows the suspension renewed past 12 Aug with DRC named. If it lapses or DRC is dropped the call is incorrect",
   "resolve_by": "2026-08-14",
   "market": "Regional",
   "segment": "City/Bush",
   "confidence": "Reported",
   "status": "correct",
   "resolved_date": "2026-08-16",
   "evidence": "Federal Register: 'Order Under Sections 362 and 365 of the PHS Act Continuing the Suspension of the Right To Introduce Certain Persons...' (doc 2026-16706, FR dated 17 Aug 2026) continues the 30-day suspension covering DRC, Uganda and South Sudan. Prior continuations 21 Jun and 13 Jul 2026. Order renewed rather than lifted, DRC still listed.",
   "source_url": "https://www.federalregister.gov/documents/2026/08/17/2026-16706/order-under-sections-362-and-365-of-the-public-health-service-act-continuing-the-suspension-of-the",
   "overdue": false
  },
  {
   "id": "P056",
   "made_date": "2026-08-06",
   "edition": "Evening Wrap",
   "claim": "The US State Department Uganda Travel Advisory will remain Level 4 through the 12 August 2026 CDC renewal decision — the 5 Aug commendation of Uganda is goodwill not an imminent downgrade",
   "resolution_criteria": "travel.state.gov Uganda advisory checked on 13 Aug 2026 still showing Level 4 Do Not Travel. If it shows Level 3 or lower on or before 12 Aug the call is incorrect",
   "resolve_by": "2026-08-13",
   "market": "UG",
   "segment": "Bush/City",
   "confidence": "Reported",
   "status": "correct",
   "resolved_date": "2026-08-16",
   "evidence": "Uganda remained at US Level 4 Do Not Travel through and beyond the 12 Aug 2026 CDC decision; travel.state.gov Uganda advisory still Level 4 (crime, health, terrorism, unrest) and the 12 Aug order retained Uganda on the covered-country list. No downgrade followed the 5 Aug commendation.",
   "source_url": "https://travel.state.gov/en/international-travel/travel-advisories/uganda.html",
   "overdue": false
  },
  {
   "id": "P058",
   "made_date": "2026-08-08",
   "edition": "Evening Wrap",
   "claim": "The WHO AFRO Weekly External Situation Report published on/around 11 Aug 2026 will show DRC cumulative confirmed Bundibugyo cases above 4053 — continued rise past the 5 Aug DRC update with no plateau",
   "resolution_criteria": "The next WHO AFRO weekly external sit-rep after the 5 Aug DRC figure shows DRC cumulative confirmed BVD cases above 4053. If it shows 4053 or fewer the call is incorrect",
   "resolve_by": "2026-08-15",
   "market": "Regional",
   "segment": "All",
   "confidence": "Confirmed",
   "status": "correct",
   "resolved_date": "2026-08-16",
   "evidence": "WHO AFRO Weekly External Situation Report 13 (data as of 9 Aug 2026, posted 11 Aug) reports DRC cumulative 4,381 confirmed cases and 2,011 confirmed deaths, CFR 45.9% — above the 4,053 threshold. +579 confirmed cases since SitRep 12.",
   "source_url": "https://www.afro.who.int/countries/democratic-republic-of-congo/publication/ebola-bundibugyo-virus-disease-outbreak-4",
   "overdue": false
  },
  {
   "id": "P062",
   "made_date": "2026-08-10",
   "edition": "Morning Brief",
   "claim": "Zanzibar's next OCGS monthly arrivals release (July 2026 data, due ~mid-Aug) will show Europe's share of arrivals above 55% — confirming the structural European concentration flagged in today's Expert Brief persists rather than easing",
   "resolution_criteria": "OCGS Zanzibar July 2026 arrivals release (published ~mid-to-late Aug 2026) shows Europe >= 55% of total arrivals. If Europe's share prints below 55% the call is incorrect",
   "resolve_by": "2026-08-31",
   "market": "ZNZ",
   "segment": "Beach",
   "confidence": "Early signal",
   "status": "correct",
   "resolved_date": "2026-08-16",
   "evidence": "OCGS Zanzibar July 2026 arrivals release: Europe supplied 60,754 of 107,801 total arrivals = 56.4%, at or above the 55% threshold. Correct but narrow — Europe's share fell from 61.9% in June.",
   "source_url": "https://www.thecitizen.co.tz/tanzania/zanzibar/",
   "overdue": false
  },
  {
   "id": "P025",
   "made_date": "2026-07-27",
   "edition": "Midday Pulse",
   "claim": "EPRA's 15 August 2026 review will set Nairobi diesel above Ksh222.86 per litre",
   "resolution_criteria": "EPRA published maximum retail petroleum price schedule effective 15 Aug 2026 showing Nairobi diesel above Ksh222.86/litre",
   "resolve_by": "2026-08-16",
   "market": "KE",
   "segment": "All",
   "confidence": "Early signal",
   "status": "incorrect",
   "resolved_date": "2026-08-15",
   "evidence": "EPRA schedule effective 15 Aug 2026 set Nairobi diesel at KSh217.86/L — a KSh5 FALL from KSh222.86, not a rise above it.",
   "source_url": "https://www.businessdailyafrica.com/bd/corporate/industry/kenya-fuel-prices-diesel-cost-drops-5558336",
   "overdue": false
  },
  {
   "id": "P028",
   "made_date": "2026-07-28",
   "edition": "Morning Brief",
   "claim": "EPRA's 15 August 2026 review will NOT fully pass through the late-July crude spike — the August Nairobi diesel rise will be under Ksh10 per litre versus the July schedule",
   "resolution_criteria": "EPRA published maximum retail petroleum price schedule effective 15 Aug 2026 showing Nairobi diesel less than Ksh10/litre above the schedule effective 15 Jul 2026",
   "resolve_by": "2026-08-16",
   "market": "KE",
   "segment": "All",
   "confidence": "Early signal",
   "status": "correct",
   "resolved_date": "2026-08-15",
   "evidence": "Nairobi diesel fell KSh5 to KSh217.86 versus the 15 Jul schedule — well inside the \"less than KSh10 above\" threshold. The late-July crude spike was not passed through.",
   "source_url": "https://www.businessdailyafrica.com/bd/corporate/industry/kenya-fuel-prices-diesel-cost-drops-5558336",
   "overdue": false
  },
  {
   "id": "P036",
   "made_date": "2026-07-29",
   "edition": "Midday Pulse (unpublished)",
   "claim": "The rendered US State Department Kenya advisory page will be revised to show the Nairobi neighbourhoods of Eastleigh and Kibera under 'Do Not Travel' rather than 'Reconsider Travel' — the web page will catch up with the 29 July RSS feed text — by 12 August 2026",
   "resolution_criteria": "travel.state.gov Kenya travel advisory page checked on 12 Aug 2026 showing Eastleigh and Kibera listed under Do Not Travel AND a revision date later than 17 March 2025. If the page still shows 'Reconsider Travel' on that date the call is incorrect and the feed's 'Increased Risk Areas' block was a generic summary, not a level change",
   "resolve_by": "2026-08-12",
   "market": "KE",
   "segment": "City",
   "confidence": "Early signal",
   "status": "correct",
   "resolved_date": "2026-08-12",
   "evidence": "Rendered travel.state.gov Kenya advisory checked 12 Aug 2026 shows 'Date issued: July 28, 2026' and lists Eastleigh and Kibera under 'Level 4 - Do Not Travel'. Both conditions met.",
   "source_url": "https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/kenya-travel-advisory.html",
   "overdue": false
  },
  {
   "id": "P046",
   "made_date": "2026-08-02",
   "edition": "Midday Pulse",
   "claim": "The rendered travel.state.gov Kenya advisory page will still carry the \"March 17, 2025\" advisory date on 1 September 2026 — confirming the 28-29 July 2026 action was a feed-level re-issue, not a content revision",
   "resolution_criteria": "travel.state.gov Kenya travel advisory page checked on 1 Sept 2026 showing header date \"March 17, 2025\". If the header shows any later date the call is incorrect.",
   "resolve_by": "2026-09-01",
   "market": "KE",
   "segment": "City",
   "confidence": "Reported",
   "status": "incorrect",
   "resolved_date": "2026-08-12",
   "evidence": "Resolved early: rendered page checked 12 Aug 2026 carries 'Date issued: July 28, 2026'. The 28-29 July action was a content revision , not a feed-level re-issue.",
   "source_url": "https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/kenya-travel-advisory.html",
   "overdue": false
  },
  {
   "id": "P040",
   "made_date": "2026-08-02",
   "edition": "Evening Wrap",
   "claim": "The rendered US State Department Kenya advisory page will still show a revision date of 17 March 2025 when checked on 12 August 2026 — the late-July RSS re-issue is administrative housekeeping and never reaches the rendered page",
   "resolution_criteria": "travel.state.gov Kenya advisory page checked on 12 Aug 2026 still displaying 'Travel Advisory March 17 2025' as its header date. If the header shows a later date the call is incorrect",
   "resolve_by": "2026-08-12",
   "market": "KE",
   "segment": "City/Bush/Beach",
   "confidence": "Reported",
   "status": "incorrect",
   "resolved_date": "2026-08-12",
   "evidence": "Rendered page checked 12 Aug 2026 shows 'Date issued: July 28, 2026' , not 17 March 2025. The late-July action did reach the rendered page.",
   "source_url": "https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/kenya-travel-advisory.html",
   "overdue": false
  },
  {
   "id": "P057",
   "made_date": "2026-08-07",
   "edition": "Morning Brief",
   "claim": "The US CDC will not post a new or renewed Section 362 Ebola entry order on its port-health page before 11 August 2026 — any renewal lands at the 12 August expiry, not early",
   "resolution_criteria": "CDC port-health evdorder page (cdc.gov/port-health/legal-authorities/evdorder.html) checked on 11 Aug 2026 still shows the 13 July 2026 order as latest with no order dated 7-10 Aug 2026. If a new order dated on/before 10 Aug appears the call is incorrect",
   "resolve_by": "2026-08-11",
   "market": "Regional",
   "segment": "Bush/City",
   "confidence": "Early signal",
   "status": "correct",
   "resolved_date": "2026-08-12",
   "evidence": "CDC port-health evdorder page checked 12 Aug 2026: last updated 20 July 2026 , 13 July 2026 order still listed as latest. No order posted 7-10 Aug.",
   "source_url": "https://www.cdc.gov/port-health/legal-authorities/evdorder.html",
   "overdue": false
  },
  {
   "id": "P030",
   "made_date": "2026-07-28",
   "edition": "Evening Wrap",
   "claim": "No East African tourism body,airline,hotel group or national tourism authority from Kenya,Uganda,Tanzania or Rwanda will appear as a commenter on US docket CDC-2026-0892 before it closes on 31 July 2026",
   "resolution_criteria": "regulations.gov docket CDC-2026-0892 comment listing reviewed after 31 Jul 2026 showing no commenter identifiably an East African tourism body,airline,hotel group or national tourism authority",
   "resolve_by": "2026-08-10",
   "market": "Regional",
   "segment": "Bush/City",
   "confidence": "Early signal",
   "status": "correct",
   "resolved_date": "2026-08-11",
   "evidence": "Regulations.gov docket CDC-2026-0892 reviewed 11 Aug 2026 (after the 31 Jul close): organisational commenters do not include any East African national tourism authority, tourism body, airline or hotel group from Kenya, Uganda, Tanzania or Rwanda. The prediction holds.",
   "source_url": "https://www.regulations.gov/docket/CDC-2026-0892",
   "overdue": false
  },
  {
   "id": "P034",
   "made_date": "2026-07-29",
   "edition": "Morning Brief",
   "claim": "Neither the US State Department nor the UK FCDO will lower its Uganda travel advisory level within 14 days of the 28 July end-of-outbreak declaration (i.e. by 11 August 2026)",
   "resolution_criteria": "travel.state.gov Uganda advisory still Level 4 AND gov.uk/foreign-travel-advice/uganda advice against travel unchanged when checked on 11 Aug 2026",
   "resolve_by": "2026-08-12",
   "market": "UG",
   "segment": "Bush/City",
   "confidence": "Reported",
   "status": "correct",
   "resolved_date": "2026-08-11",
   "evidence": "Checked 11 Aug 2026: US State Dept Uganda advisory remains Level 4 'Do Not Travel' (unchanged since the 28 Jul end-of-outbreak declaration, reaffirmed in the 5 Aug Ebola Response Update) and no FCDO downgrade of Uganda advice was reported. Neither government lowered its level within 14 days — call holds.",
   "source_url": "https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/uganda-travel-advisory.html",
   "overdue": false
  },
  {
   "id": "P053",
   "made_date": "2026-08-05",
   "edition": "Morning Brief",
   "claim": "The next WHO AFRO Weekly External Situation Report (published Tuesdays) will show cumulative DRC confirmed Bundibugyo cases above 3605 — continued rise, no plateau after epi-week 30's record 567 cases",
   "resolution_criteria": "The next WHO AFRO weekly external sit-rep after the 30 Jul cut-off showing DRC cumulative confirmed BVD cases above 3605. If it shows 3605 or fewer the call is incorrect",
   "resolve_by": "2026-08-13",
   "market": "Regional",
   "segment": "All",
   "confidence": "Confirmed",
   "status": "correct",
   "resolved_date": "2026-08-06",
   "evidence": "WHO/ECDC weekly reporting 4 Aug 2026: DRC 3874 confirmed , 1751 deaths (data to 3 Aug) — exceeds the 3605 threshold; outbreak now largest in DRC history",
   "source_url": "https://www.afro.who.int/health-topics/ebola-disease/outbreak-drc-26",
   "overdue": false
  },
  {
   "id": "P021",
   "made_date": "2026-07-27",
   "edition": "Morning Brief",
   "claim": "DRC's confirmed Bundibugyo case count will exceed 4,000 before Uganda's Ebola outbreak is declared over",
   "resolution_criteria": "DRC health ministry,WHO AFRO or ECDC figures showing cumulative confirmed cases above 4,000 dated before any WHO/Uganda end-of-outbreak declaration",
   "resolve_by": "2026-10-31",
   "market": "Regional",
   "segment": "All",
   "confidence": "Reported",
   "status": "incorrect",
   "resolved_date": "2026-08-03",
   "evidence": "Uganda MoH declared the outbreak over on 28 July 2026 (30 days early) with DRC at ~3,605 confirmed as at 30 July (WHO) — below the 4,000 threshold. The declaration preceded the caseload reaching 4,000 so the call fails.",
   "source_url": "https://www.aljazeera.com/news/2026/7/30/congos-ebola-death-toll-passes-1500-as-it-struggles-to-halt-spread",
   "overdue": false
  },
  {
   "id": "P038",
   "made_date": "2026-07-29",
   "edition": "Midday Pulse (unpublished)",
   "claim": "At least one Kenyan national news outlet will report the 29 July US Kenya advisory re-issue on or before 3 August 2026 — measuring our lead time over the domestic press on a tier-1 advisory action",
   "resolution_criteria": "A search of Kenyan national outlets (Nation,Standard,Star,Citizen,Business Daily) on 3 Aug 2026 returning a story published 29 Jul-3 Aug 2026 about the updated US Kenya travel advisory. Radar first_seen for the feed item was 2026-07-29T11:04+03:00",
   "resolve_by": "2026-08-03",
   "market": "KE",
   "segment": "City",
   "confidence": "Early signal",
   "status": "incorrect",
   "resolved_date": "2026-08-03",
   "evidence": "Search of Kenyan outlets (Nation,Standard,Star,Citizen,Business Daily) on 3 Aug 2026 found no story published 29 Jul-3 Aug on the 29 July re-issue. Only circulating US-Kenya advisory item is a Citizen Digital piece published 18 March 2025 (modified_time 2026-08-02) — an 18-month-old article silently re-dated, recycling not fresh reporting. Primary travel.state.gov page read directly 3 Aug still dated 17 March 2025 with Eastleigh/Kibera at Reconsider Travel. Domestic press did not independently report the re-issue.",
   "source_url": "https://travel.state.gov/_res/rss/TAsTWs.xml",
   "overdue": false
  },
  {
   "id": "P039",
   "made_date": "2026-07-30",
   "edition": "Evening Wrap",
   "claim": "DR Congo's cumulative confirmed Bundibugyo cases will exceed 3600 by the WHO AFRO External Situation Report dated on or around 2 August 2026 — i.e. the outbreak has NOT plateaued and the US regional entry ban has no epidemiological basis to lift on Uganda's timeline",
   "resolution_criteria": "A WHO AFRO Weekly External Situation Report (issue 12 or later) published between 30 Jul and 9 Aug 2026 stating a cumulative confirmed DRC case count above 3600. If the next SitRep shows 3600 or fewer the call is incorrect",
   "resolve_by": "2026-08-09",
   "market": "Regional",
   "segment": "Bush/City",
   "confidence": "Reported",
   "status": "correct",
   "resolved_date": "2026-08-03",
   "evidence": "WHO Disease Outbreak News: 3605 confirmed , 1587 deaths , CFR 44% as at 30 Jul 2026 — exceeds the 3600 threshold",
   "source_url": "https://www.who.int/emergencies/disease-outbreak-news/item/2026-DON614",
   "overdue": false
  },
  {
   "id": "P001",
   "made_date": "2026-07-25",
   "edition": "Special Edition",
   "claim": "Uganda's Ebola outbreak will be formally declared over on or about 27 August 2026",
   "resolution_criteria": "WHO or Uganda MoH issues a formal end-of-outbreak declaration by 5 Sept 2026",
   "resolve_by": "2026-09-05",
   "market": "UG",
   "segment": "Bush/City",
   "confidence": "Confirmed",
   "status": "partial",
   "resolved_date": "2026-07-29",
   "evidence": "Uganda MoH declared the outbreak over on 28 July 2026 — criterion met (declaration before 5 Sept) but 30 days earlier than the claimed 'on or about 27 August'. Uganda counted 42 days from the 16 June discharge of the last Ugandan national, not from the 16 July discharge WHO AFRO dated the countdown to.",
   "source_url": "https://health.go.ug/uganda-is-officially-ebola-free/",
   "overdue": false
  },
  {
   "id": "P018",
   "made_date": "2026-07-26",
   "edition": "Sunday Foresight",
   "claim": "DRC's Ebola outbreak will exceed 3,000 confirmed cases before Uganda's outbreak is declared over",
   "resolution_criteria": "ECDC Communicable Disease Threats Report or DRC INSP situation report showing cumulative confirmed cases above 3,000 dated before the WHO/Uganda end-of-outbreak declaration",
   "resolve_by": "2026-09-30",
   "market": "Regional",
   "segment": "All",
   "confidence": "Reported",
   "status": "correct",
   "resolved_date": "2026-07-27",
   "evidence": "DRC health authorities released updated figures on Saturday 25 July 2026 showing 3,075 confirmed Bundibugyo cases , 1,354 deaths and 556 recoveries across five provinces — above the 3,000 threshold and before any Uganda end-of-outbreak declaration. Relayed by Xinhua and Africanews , 26 July 2026.",
   "source_url": "https://www.africanews.com/2026/07/26/dr-congo-says-the-number-of-confirmed-ebola-cases-has-surpassed-3000/",
   "overdue": false
  }
 ]
};
