window.LEDGER = {
 "updated": "2026-07-28 08:23",
 "stats": {
  "total": 29,
  "open": 28,
  "resolved": 1,
  "correct": 1,
  "partial": 0,
  "incorrect": 0,
  "accuracy": 100
 },
 "open": [
  {
   "id": "P025",
   "made_date": "2026-07-27",
   "edition": "Midday Pulse",
   "claim": "EPRA's 15 August 2026 review will set Nairobi diesel above Ksh222.86 per litre",
   "resolution_criteria": "EPRA published maximum retail petroleum price schedule effective 15 Aug 2026 showing Nairobi diesel above Ksh222.86/litre",
   "resolve_by": "2026-08-16",
   "market": "KE",
   "segment": "All",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.kenyans.co.ke/news/125567-govt-raises-fuel-price-concerns-ahead-august-epra-review",
   "overdue": false
  },
  {
   "id": "P028",
   "made_date": "2026-07-28",
   "edition": "Morning Brief",
   "claim": "EPRA's 15 August 2026 review will NOT fully pass through the late-July crude spike — the August Nairobi diesel rise will be under Ksh10 per litre versus the July schedule",
   "resolution_criteria": "EPRA published maximum retail petroleum price schedule effective 15 Aug 2026 showing Nairobi diesel less than Ksh10/litre above the schedule effective 15 Jul 2026",
   "resolve_by": "2026-08-16",
   "market": "KE",
   "segment": "All",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.standardmedia.co.ke/business/financial-standard/article/2001553910/of-fuel-crisis-and-rutos-fresh-headache",
   "overdue": false
  },
  {
   "id": "P023",
   "made_date": "2026-07-27",
   "edition": "Morning Brief",
   "claim": "The US CDC will renew its DRC/Uganda/South Sudan Ebola entry restrictions again at the mid-August decision point rather than let them lapse",
   "resolution_criteria": "CDC returning-traveller guidance or Federal Register notice showing the entry restriction order extended beyond 12 August 2026",
   "resolve_by": "2026-08-25",
   "market": "Regional",
   "segment": "All",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.cdc.gov/ebola/situation-summary/returning-travelers.html",
   "overdue": false
  },
  {
   "id": "P001",
   "made_date": "2026-07-25",
   "edition": "Special Edition",
   "claim": "Uganda's Ebola outbreak will be formally declared over on or about 27 August 2026",
   "resolution_criteria": "WHO or Uganda MoH issues a formal end-of-outbreak declaration by 5 Sept 2026",
   "resolve_by": "2026-09-05",
   "market": "UG",
   "segment": "Bush/City",
   "confidence": "Confirmed",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P007",
   "made_date": "2026-07-25",
   "edition": "Special Edition",
   "claim": "Rwanda's 30-day DRC entry restriction will remain in force after Uganda's Ebola outbreak is declared over",
   "resolution_criteria": "Rwanda MoH notice still lists the 30-day DRC entry denial 14 days after the WHO/Uganda end-of-outbreak declaration",
   "resolve_by": "2026-09-15",
   "market": "RW",
   "segment": "Bush/City",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P012",
   "made_date": "2026-07-26",
   "edition": "Morning Brief",
   "claim": "Zanzibar's July 2026 arrivals will show year-on-year growth below 10%",
   "resolution_criteria": "Zanzibar Commission for Tourism July 2026 arrivals figure is less than 10% above July 2025's 106,108",
   "resolve_by": "2026-09-15",
   "market": "ZNZ",
   "segment": "Beach",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P029",
   "made_date": "2026-07-28",
   "edition": "Morning Brief",
   "claim": "MV Adan will still be aground off Nyali beach on 1 September 2026 — the mid-August refloating window will slip",
   "resolution_criteria": "Kenya Maritime Authority statement,Kenyan press or KPA notice confirming MV Adan remains aground on or after 1 Sep 2026",
   "resolve_by": "2026-09-15",
   "market": "KE",
   "segment": "Beach",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.standardmedia.co.ke/business/shipping-logistics/article/2001553863/kma-explains-delay-in-salvaging-grounded-ship-off-nyali-beach",
   "overdue": false
  },
  {
   "id": "P017",
   "made_date": "2026-07-26",
   "edition": "Midday Pulse",
   "claim": "Uganda's 25-27 September park waiver will cover entry fees only — game drives , boat cruises and permits remain chargeable",
   "resolution_criteria": "UWA or Ministry of Tourism published notice confirming scope of the free-entry days as entry fees only",
   "resolve_by": "2026-09-24",
   "market": "UG",
   "segment": "Bush",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P002",
   "made_date": "2026-07-25",
   "edition": "Special Edition",
   "claim": "The US State Department will NOT lower Uganda from Level 4 within 30 days of the outbreak being declared over",
   "resolution_criteria": "State Dept Uganda advisory still Level 4 thirty days after the WHO declaration",
   "resolve_by": "2026-09-26",
   "market": "UG",
   "segment": "Bush/City",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P027",
   "made_date": "2026-07-28",
   "edition": "Morning Brief",
   "claim": "The KAWU aviation strike suspension will hold — no nationwide Kenyan aviation strike or JKIA industrial action will actually commence before 30 September 2026",
   "resolution_criteria": "No reported commencement of a KAWU nationwide strike or JKIA work stoppage in Kenyan press,KAA or KCAA notices between 28 Jul and 30 Sep 2026",
   "resolve_by": "2026-09-30",
   "market": "KE",
   "segment": "All",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.the-star.co.ke/news/2026-07-27-aviation-workers-suspend-strike-pave-way-for-talks",
   "overdue": false
  },
  {
   "id": "P003",
   "made_date": "2026-07-24",
   "edition": "Evening Wrap",
   "claim": "Kenya peak-season arrivals hold up despite political rhetoric discouraging visitors",
   "resolution_criteria": "August 2026 arrivals at or above August 2025 (277,155) per Tourism Research Institute or ministry data",
   "resolve_by": "2026-10-15",
   "market": "KE",
   "segment": "All",
   "confidence": "Confirmed",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P008",
   "made_date": "2026-07-25",
   "edition": "Special Edition",
   "claim": "Entebbe international arrivals fall again year-on-year in Q2 2026 following the Q1 decline of 7.9%",
   "resolution_criteria": "UCAA or Aviation Week Q2 2026 figures below Q2 2025",
   "resolve_by": "2026-10-31",
   "market": "UG",
   "segment": "All",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P009",
   "made_date": "2026-07-25",
   "edition": "Evening Wrap",
   "claim": "No Kenyan court will order a halt to operations at any Maasai Mara reserve camp before the 2026 crossing season ends",
   "resolution_criteria": "No ELC or appellate order suspending operations of Ritz-Carlton Mara , Sala's Camp or Elewana Sand River reported by Business Daily or published on Kenya Law by 31 Oct 2026",
   "resolve_by": "2026-10-31",
   "market": "KE",
   "segment": "Bush",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P011",
   "made_date": "2026-07-26",
   "edition": "Morning Brief",
   "claim": "Tanzania's Fair Competition Commission will clear the A Squared Holding / Nawiri Group transaction without divestiture conditions",
   "resolution_criteria": "FCC issues an unconditional clearance decision on the A Squared / Nawiri merger as reported by the FCC register , TanzaniaInvest or Tanzanian business press",
   "resolve_by": "2026-10-31",
   "market": "TZ",
   "segment": "Bush",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P021",
   "made_date": "2026-07-27",
   "edition": "Morning Brief",
   "claim": "DRC's confirmed Bundibugyo case count will exceed 4,000 before Uganda's Ebola outbreak is declared over",
   "resolution_criteria": "DRC health ministry,WHO AFRO or ECDC figures showing cumulative confirmed cases above 4,000 dated before any WHO/Uganda end-of-outbreak declaration",
   "resolve_by": "2026-10-31",
   "market": "Regional",
   "segment": "All",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.africanews.com/2026/07/26/dr-congo-says-the-number-of-confirmed-ebola-cases-has-surpassed-3000/",
   "overdue": false
  },
  {
   "id": "P026",
   "made_date": "2026-07-27",
   "edition": "Midday Pulse",
   "claim": "Exercise Haraka Storm will be conducted in Tanzania rather than Kenya during September-November 2026",
   "resolution_criteria": "UK MoD,British Army or reputable press reporting Exercise Haraka Storm held in Tanzania between 1 Sep and 30 Nov 2026",
   "resolve_by": "2026-12-15",
   "market": "KE",
   "segment": "Bush",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.standardmedia.co.ke/national/article/2001553563/why-uk-moved-batuk-training-to-tanzania",
   "overdue": false
  },
  {
   "id": "P015",
   "made_date": "2026-07-26",
   "edition": "Midday Pulse",
   "claim": "At least one further Kenyan hotel of 100+ rooms will be placed under administration or receivership by a lender before 31 Dec 2026",
   "resolution_criteria": "A gazetted Insolvency Act notice or Business Daily , Khusoko report of a 100+ room Kenyan hotel entering administration or receivership between 27 Jul and 31 Dec 2026",
   "resolve_by": "2026-12-31",
   "market": "KE",
   "segment": "City/Beach",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P022",
   "made_date": "2026-07-27",
   "edition": "Morning Brief",
   "claim": "No Bundibugyo vaccine will be licensed or deployed for outbreak use in DRC or Uganda before 31 December 2026 — the DRC Prime Minister's \"two to four months\" timeline will not hold",
   "resolution_criteria": "No WHO prequalification,emergency use listing or national regulatory approval of a Bundibugyo-specific vaccine and no ring or mass vaccination campaign reported by WHO,Africa CDC or Oxford Vaccine Group by 31 Dec 2026",
   "resolve_by": "2026-12-31",
   "market": "Regional",
   "segment": "All",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.ox.ac.uk/news/2026-07-24-first-volunteer-vaccinated-in-the-worlds-first-bundibugyo-ebolavirus-vaccine-trial",
   "overdue": false
  },
  {
   "id": "P024",
   "made_date": "2026-07-27",
   "edition": "Midday Pulse",
   "claim": "Kenya will not renew BATUK's training licences before 31 December 2026",
   "resolution_criteria": "UK MoD,British High Commission Nairobi or Kenyan Ministry of Defence announcement confirming renewal of BATUK training licences published by 31 Dec 2026",
   "resolve_by": "2026-12-31",
   "market": "KE",
   "segment": "Bush/City",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.standardmedia.co.ke/rift-valley/article/2001553819/shadow-of-impunity-how-years-of-alleged-atrocities-finally-led-to-batuks-departure-from-kenya",
   "overdue": false
  },
  {
   "id": "P006",
   "made_date": "2026-07-25",
   "edition": "Morning Brief",
   "claim": "Regional airlift into East Africa continues expanding faster than rate discipline can absorb",
   "resolution_criteria": "Net seat capacity into NBO/EBB/ZNZ/KGL up year-on-year while published lead-in rates flat or down",
   "resolve_by": "2027-01-31",
   "market": "Regional",
   "segment": "All",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P010",
   "made_date": "2026-07-25",
   "edition": "Evening Wrap",
   "claim": "Uganda's 10-year tourism tax holiday will not produce a publicly announced branded hotel signing of US$10m or more before FHS Africa Kampala",
   "resolution_criteria": "No Uganda hotel investment of US$10m+ announced by Uganda Investment Authority , UTB or hospitality trade press between 25 Jul 2026 and 3 Feb 2027",
   "resolve_by": "2027-02-03",
   "market": "UG",
   "segment": "City/Bush",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P004",
   "made_date": "2026-07-24",
   "edition": "Morning Brief",
   "claim": "Nairobi hotel occupancy or ADR comes under measurable pressure as ~1,500 branded rooms open in 2026",
   "resolution_criteria": "Published Nairobi occupancy or ADR for H2 2026 below the equivalent 2025 period",
   "resolve_by": "2027-03-31",
   "market": "KE",
   "segment": "City",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P014",
   "made_date": "2026-07-26",
   "edition": "Midday Pulse",
   "claim": "Glee Hotel will change hands via the administrator rather than return to Mary Wambui Mungai's control",
   "resolution_criteria": "Administrator's report or Business Daily , Khusoko reporting a completed sale , transfer or new owner of Glee Hotel Limited by 31 Mar 2027",
   "resolve_by": "2027-03-31",
   "market": "KE",
   "segment": "City",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P019",
   "made_date": "2026-07-26",
   "edition": "Sunday Foresight",
   "claim": "Rwanda's DRC arrivals will fall year-on-year in H2 2026 as the 30-day entry restriction bites",
   "resolution_criteria": "RDB or NISR H2 2026 / full-year 2026 arrivals data showing DRC arrivals below the H2 2025 equivalent",
   "resolve_by": "2027-04-30",
   "market": "RW",
   "segment": "City/Bush",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P013",
   "made_date": "2026-07-26",
   "edition": "Morning Brief",
   "claim": "Rwanda's MICE revenue will exceed US$100m for the first time in calendar 2026",
   "resolution_criteria": "RDB 2026 Annual Report reports MICE revenue above US$100 million",
   "resolve_by": "2027-05-31",
   "market": "RW",
   "segment": "City",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P005",
   "made_date": "2026-07-24",
   "edition": "Midday Pulse",
   "claim": "Zanzibar branded all-inclusive supply growth pressures independent resort rate benchmarks",
   "resolution_criteria": "Evidence of independent Zanzibar resorts cutting published rates or reporting allocation loss into 2027",
   "resolve_by": "2027-06-30",
   "market": "ZNZ",
   "segment": "Beach",
   "confidence": "Early signal",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P016",
   "made_date": "2026-07-26",
   "edition": "Midday Pulse",
   "claim": "Kenya will not cut or remove the airport passenger levy on air tickets before 31 Dec 2027",
   "resolution_criteria": "No Finance Act , gazette notice or KCAA/KAA announcement reducing or abolishing the airport passenger service levy published by 31 Dec 2027",
   "resolve_by": "2027-12-31",
   "market": "KE",
   "segment": "All",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "",
   "overdue": false
  },
  {
   "id": "P020",
   "made_date": "2026-07-26",
   "edition": "Sunday Foresight",
   "claim": "Uganda Airlines' Boeing 737-8 MAX and 787-9 order will not deliver a first aircraft before 31 December 2027",
   "resolution_criteria": "No Uganda Airlines 737-8 or 787-9 delivery reported by the airline,Boeing,ch-aviation or Ugandan press by 31 Dec 2027",
   "resolve_by": "2027-12-31",
   "market": "UG",
   "segment": "City",
   "confidence": "Reported",
   "status": "open",
   "resolved_date": "",
   "evidence": "",
   "source_url": "https://www.newvision.co.ug/category/business/uganda-airlines-orders-eight-boeing-jets-to-e-NV_237451_072026",
   "overdue": false
  }
 ],
 "resolved": [
  {
   "id": "P018",
   "made_date": "2026-07-26",
   "edition": "Sunday Foresight",
   "claim": "DRC's Ebola outbreak will exceed 3,000 confirmed cases before Uganda's outbreak is declared over",
   "resolution_criteria": "ECDC Communicable Disease Threats Report or DRC INSP situation report showing cumulative confirmed cases above 3,000 dated before the WHO/Uganda end-of-outbreak declaration",
   "resolve_by": "2026-09-30",
   "market": "Regional",
   "segment": "All",
   "confidence": "Reported",
   "status": "correct",
   "resolved_date": "2026-07-27",
   "evidence": "DRC health authorities released updated figures on Saturday 25 July 2026 showing 3,075 confirmed Bundibugyo cases , 1,354 deaths and 556 recoveries across five provinces — above the 3,000 threshold and before any Uganda end-of-outbreak declaration. Relayed by Xinhua and Africanews , 26 July 2026.",
   "source_url": "https://www.africanews.com/2026/07/26/dr-congo-says-the-number-of-confirmed-ebola-cases-has-surpassed-3000/",
   "overdue": false
  }
 ]
};
