window.RATE_INDEX = {
 "updated": "2026-10-02 10:51",
 "convention": {
  "los": 2,
  "lead_days": 30,
  "occupancy": "2 adults",
  "currency": "USD"
 },
 "minN": 3,
 "lookbackWeeks": 6,
 "method": "chain-linked matched-sample",
 "methodNote": "Each property is compared only with itself, so the index measures rate MOVEMENT validly even though the basket mixes meal bases and rate types. Raw medians are context only and are not comparable across markets — check levelComparable before quoting a level.",
 "wowNote": "wow is the matched-sample link for the latest week. wowClean is the same link computed only on pairs whose meal basis was KNOWN and UNCHANGED between the two weeks; basisChangedPairs counts the pairs excluded from it. Where basisChangedPairs is large relative to matched, the headline wow is partly a re-basing artefact — quote wowClean, or quote no move at all.",
 "spreadNote": "Commission-leakage spread = median of (OTA rate / direct rate - 1) for the same property in the same week. Computed only where the direct rate is room-only or B&B, since an OTA lowest rate is not comparable with a fully-inclusive safari rate. Markets where no property qualifies report null.",
 "totalObservations": 0,
 "distinctProperties": 0,
 "basketSize": 134,
 "markets": {
  "nairobi": {
   "label": "Nairobi",
   "segment": "city",
   "country": "KE",
   "basketSize": 16,
   "series": [],
   "baseline": null,
   "latest": null,
   "wow": null,
   "wowClean": null,
   "basisChangedPairs": null,
   "basisMix": {},
   "rateTypeMix": {},
   "levelComparable": false,
   "residentOnly": false,
   "ota": null,
   "spread": null,
   "spreadLatest": null
  },
  "coast": {
   "label": "Mombasa & Diani",
   "segment": "beach",
   "country": "KE",
   "basketSize": 13,
   "series": [],
   "baseline": null,
   "latest": null,
   "wow": null,
   "wowClean": null,
   "basisChangedPairs": null,
   "basisMix": {},
   "rateTypeMix": {},
   "levelComparable": false,
   "residentOnly": false,
   "ota": null,
   "spread": null,
   "spreadLatest": null
  },
  "zanzibar": {
   "label": "Zanzibar",
   "segment": "beach",
   "country": "ZNZ",
   "basketSize": 12,
   "series": [],
   "baseline": null,
   "latest": null,
   "wow": null,
   "wowClean": null,
   "basisChangedPairs": null,
   "basisMix": {},
   "rateTypeMix": {},
   "levelComparable": false,
   "residentOnly": false,
   "ota": null,
   "spread": null,
   "spreadLatest": null
  },
  "kigali": {
   "label": "Kigali",
   "segment": "city",
   "country": "RW",
   "basketSize": 11,
   "series": [],
   "baseline": null,
   "latest": null,
   "wow": null,
   "wowClean": null,
   "basisChangedPairs": null,
   "basisMix": {},
   "rateTypeMix": {},
   "levelComparable": false,
   "residentOnly": false,
   "ota": null,
   "spread": null,
   "spreadLatest": null
  },
  "kampala": {
   "label": "Kampala & Entebbe",
   "segment": "city",
   "country": "UG",
   "basketSize": 12,
   "series": [],
   "baseline": null,
   "latest": null,
   "wow": null,
   "wowClean": null,
   "basisChangedPairs": null,
   "basisMix": {},
   "rateTypeMix": {},
   "levelComparable": false,
   "residentOnly": false,
   "ota": null,
   "spread": null,
   "spreadLatest": null
  },
  "safari": {
   "label": "Mara & Serengeti",
   "segment": "bush",
   "country": "KE/TZ",
   "basketSize": 22,
   "series": [],
   "baseline": null,
   "latest": null,
   "wow": null,
   "wowClean": null,
   "basisChangedPairs": null,
   "basisMix": {},
   "rateTypeMix": {},
   "levelComparable": false,
   "residentOnly": false,
   "ota": null,
   "spread": null,
   "spreadLatest": null
  },
  "dar_arusha": {
   "label": "Dar es Salaam & Arusha",
   "segment": "city",
   "country": "TZ",
   "basketSize": 9,
   "series": [],
   "baseline": null,
   "latest": null,
   "wow": null,
   "wowClean": null,
   "basisChangedPairs": null,
   "basisMix": {},
   "rateTypeMix": {},
   "levelComparable": false,
   "residentOnly": false,
   "ota": null,
   "spread": null,
   "spreadLatest": null
  },
  "lakevictoria": {
   "label": "Lake Victoria & Entebbe",
   "segment": "beach",
   "country": "UG",
   "basketSize": 9,
   "series": [],
   "baseline": null,
   "latest": null,
   "wow": null,
   "wowClean": null,
   "basisChangedPairs": null,
   "basisMix": {},
   "rateTypeMix": {},
   "levelComparable": false,
   "residentOnly": false,
   "ota": null,
   "spread": null,
   "spreadLatest": null
  },
  "bwindi": {
   "label": "Bwindi, Kibale & QENP",
   "segment": "bush",
   "country": "UG",
   "basketSize": 10,
   "series": [],
   "baseline": null,
   "latest": null,
   "wow": null,
   "wowClean": null,
   "basisChangedPairs": null,
   "basisMix": {},
   "rateTypeMix": {},
   "levelComparable": false,
   "residentOnly": false,
   "ota": null,
   "spread": null,
   "spreadLatest": null
  },
  "lakekivu": {
   "label": "Lake Kivu",
   "segment": "beach",
   "country": "RW",
   "basketSize": 10,
   "series": [],
   "baseline": null,
   "latest": null,
   "wow": null,
   "wowClean": null,
   "basisChangedPairs": null,
   "basisMix": {},
   "rateTypeMix": {},
   "levelComparable": false,
   "residentOnly": false,
   "ota": null,
   "spread": null,
   "spreadLatest": null
  },
  "volcanoes": {
   "label": "Volcanoes & Akagera",
   "segment": "bush",
   "country": "RW",
   "basketSize": 10,
   "series": [],
   "baseline": null,
   "latest": null,
   "wow": null,
   "wowClean": null,
   "basisChangedPairs": null,
   "basisMix": {},
   "rateTypeMix": {},
   "levelComparable": false,
   "residentOnly": false,
   "ota": null,
   "spread": null,
   "spreadLatest": null
  }
 },
 "benchmarks": {
  "updated": "2026-07-24",
  "items": [
   {
    "market": "Nairobi",
    "metric": "Short-let ADR",
    "value": "US$47",
    "period": "2026",
    "source": "AirDNA",
    "url": "https://www.airdna.co/vacation-rental-data/app/ke/default/nairobi/overview",
    "note": "Short-term rental market, not branded hotels — a demand-side proxy."
   },
   {
    "market": "Nairobi",
    "metric": "Short-let occupancy",
    "value": "41%",
    "period": "2026",
    "source": "AirDNA",
    "url": "https://www.airdna.co/vacation-rental-data/app/ke/default/nairobi/overview",
    "note": "Across ~13,110 active listings."
   },
   {
    "market": "Nairobi",
    "metric": "Short-let RevPAR",
    "value": "US$19",
    "period": "2026",
    "source": "AirDNA",
    "url": "https://www.airdna.co/vacation-rental-data/app/ke/default/nairobi/overview",
    "note": "Rate weighted by occupancy."
   },
   {
    "market": "Nairobi",
    "metric": "Branded room pipeline",
    "value": "~3,650 rooms",
    "period": "Q1 2026",
    "source": "W Hospitality Group via Tourism Update",
    "url": "https://www.tourismupdate.com/article/is-nairobi-building-too-many-hotels",
    "note": "~1,500 rooms opening in 2026; occupancy already off ~10pts since 2023."
   },
   {
    "market": "Zanzibar",
    "metric": "Annual arrivals",
    "value": "917,167",
    "period": "2025",
    "source": "Zanzibar tourism data via Travel And Tour World",
    "url": "https://www.travelandtourworld.com/",
    "note": "Up roughly 24% on 2024."
   },
   {
    "market": "Tanzania",
    "metric": "Tourism earnings",
    "value": "US$4.41bn",
    "period": "2025",
    "source": "Tanzania national statistics",
    "url": "https://www.tanzaniatourism.go.tz/",
    "note": "Record high; 2,294,495 international arrivals."
   }
  ]
 }
};
