// EA Pulse regulatory tracker — levies, fees, permits and entry rules.
// Maintained by the daily Pulse task. Every entry carries a source; anything
// unverified is flagged so readers never act on a stale number unknowingly.
window.RULES = {
 updated: "4 September 2026 (morning — ADDED: EU Air Safety List operating ban on all Tanzanian-certified airlines RETAINED in the 48th update, 9 June 2026; the ban is on regulator oversight, not aircraft, and a widely circulated 'ban lifted' trade item from Sep 2025 is false. Standing: Kenya's US$50,000 travel-health insurance rule remains SUSPENDED by High Court conservatory orders of 21 Aug 2026, hearing 16 Sep 2026. EU Directive (EU) 2024/825 (EmpCo) green-claims rules apply from 27 Sep 2026.)",
 groups: [
  { country:"Source-market rules (EU)", flag:"🇪🇺", items:[
    {rule:"EU green-claims rules \u2014 Directive (EU) 2024/825 (EmpCo)", amount:"No fee \u2014 a marketing compliance obligation", who:"Any hotel, lodge, camp, resort or operator making environmental claims to consumers in the EU, regardless of where the business is based", effective:"Applies from 27 September 2026 (member-state transposition was due 27 March 2026)", note:"Bans generic environmental claims \u2014 'eco-friendly', 'green', 'sustainable', 'responsible' \u2014 unless a recognised certification directly covers the claim. Bans 'carbon neutral' and 'climate compensated' where the claim rests on offsets outside the value chain. Bans self-created labels and badges. Broad claims survive only under an EU Ecolabel or an EN ISO 14024 Type I ecolabel. Schemes named as meeting the third-party verification bar include Travelife, Green Key, Green Globe, EarthCheck and Green Destinations. PRACTICAL POINT: the penalty exposure sits with the EU trader \u2014 the tour operator, package organiser or OTA reselling you \u2014 under the Unfair Commercial Practices Directive that EmpCo amends, which carries maximum fines of at least 4% of annual turnover in the member states concerned. Expect substantiation requests to arrive contractually from European agents rather than from a regulator.", source:"Directive (EU) 2024/825 (EUR-Lex); European Commission; Sustainable Travel International guide, 5 Aug 2026", verified:true, flag:"action"},
   ]},
  { country:"Kenya", flag:"🇰🇪", items:[
    {rule:"Electronic Travel Authorisation (ETA)", amount:"US$30", who:"All non-EAC visitors, including infants", effective:"In force since Jan 2024", note:"Online only; typically 24–72h. Apply before travel — there is no visa on arrival.", source:"Kenya eTA portal", verified:true},
    {rule:"Maasai Mara park fee", amount:"US$100 low / US$200 peak", who:"Non-resident adult, per person per day", effective:"Current 2026 season", note:"Peak pricing bites during migration — build it into quoted rates. Operator schedules for 2026 also describe a 12-hour ticket validity, meaning an overnight inside the reserve triggers a second entry charge, and fees no longer varying by camp location. We have not seen the Narok County gazette — CONFIRM before quoting.", source:"Narok County / operator schedules", verified:false},
    {rule:"KWS park fees (Amboseli, Nakuru, Tsavo)", amount:"US$80–90 per day", who:"Non-resident adult", effective:"Current", note:"Paid via kwspay.ecitizen.go.ke. Nairobi NP US$80.", source:"Kenya Wildlife Service", verified:true},
    {rule:"Tourism levy on short-term rentals", amount:"2% of booking value", who:"Airbnb, Booking.com and other STR platform listings", effective:"Reported for June 2026 — CONFIRM before quoting", note:"Extends the existing 2% Tourism Fund levy to short-term rentals, collected at source by platforms, with host registration required by the Tourism Regulatory Authority. Trade-press reported; we have not yet seen the gazette notice.", source:"Tourism Fund / trade press", verified:false},
    {rule:"Airport passenger levy (JKIA financing)", amount:"No rate change announced", who:"Every international and domestic air ticket sold in Kenya", effective:"In force; Sh18.5bn/yr earmarked to airport debt", note:"Kenya will borrow Sh81bn of a Sh116bn JKIA package, with a bond secured against FUTURE passenger levy collections. No rate rise has been announced — but a levy pledged to bondholders is structurally very hard to cut. Do not model Kenyan air-tax relief into 2027–28 rate cards; write the cost into net-rate contracts instead.", source:"Business Daily / Daily Nation, 24 Jul 2026", verified:true, flag:"action"},
    {rule:"Mandatory travel-health insurance", amount:"US$50,000 minimum cover", who:"Most international arrivals", effective:"Gazetted 30 Jul 2026 — SUSPENDED by court order 21 Aug 2026; hearing 16 Sep 2026", note:"SUSPENDED BY COURT ORDER. The High Court at Marsabit (Justice Francis Rayola Olel) issued conservatory orders on 21 Aug 2026 halting enforcement of Gazette Notice No. 11492 pending determination of a constitutional petition; heard inter partes 16 Sep 2026. Petitioners Edow Issack Mohammed and Zhulekha Mohamed Edin argue the Ministry of Health lacks mandate over entry conditions (Interior/Immigration under the Citizenship and Immigration Act 2011), that it encroaches on the IRA, and that uploading health data via the eTA breaches Article 31 privacy. This is the SECOND petition filed; a separate COFEK challenge (mention 29 Sep 2026) runs alongside. The gazette set minimum cover of US$50,000 — reported as US$20,000 medical plus US$25,000 emergency evacuation plus repatriation, mental-health and prescription benefits — under the Social Health Insurance Act. Quote packages without it, but retain the clause in 2027 contracts: the 16 Sep hearing can restore it.", source:"Kenya Gazette 30 Jul 2026 / Kahawatungu & The Standard, 24-25 Aug 2026 (order dated 21 Aug 2026)", verified:true, flag:"action"},
    {rule:"COVID-19 entry requirements", amount:"None", who:"All", effective:"Fully lifted", note:"No testing, vaccination proof or quarantine. Remove any legacy wording from your pre-arrival comms.", source:"Ministry of Health", verified:true}
  ]},
  { country:"Uganda", flag:"🇺🇬", items:[
    {rule:"Tourist e-Visa", amount:"US$50 + US$1.50 admin", who:"Single entry, up to 90 days", effective:"Current", note:"NO visa on arrival — e-Visa is the only route. Guests must print the approval letter.", source:"Uganda e-Visa portal", verified:true},
    {rule:"Gorilla permit (Bwindi & Mgahinga)", amount:"US$800", who:"Foreign non-resident", effective:"Current", note:"US$700 foreign resident · US$500 African · UGX 300,000 EAC citizens.", source:"Uganda Wildlife Authority", verified:true},
    {rule:"Low-season gorilla permit discount", amount:"US$600 (from US$800)", who:"Foreign non-resident", effective:"April, May & November", note:"Introduced Feb 2026. A genuine packaging opportunity — sell the shoulder season on price.", source:"Uganda Wildlife Authority", verified:true},
    {rule:"Ebola outbreak status", amount:"Declared OVER \u2014 WHO-certified", who:"All visitors", effective:"Uganda MoH 28 July 2026; WHO certification 26 August 2026", note:"WHO confirmed on 26 Aug 2026 that Uganda cleared the 42-day monitoring period with no new transmission, announced with the Ministry of Health. Uganda's outbreak totalled 20 confirmed cases and 2 deaths; last confirmed case 21 June, last patient discharged from Mulago 16 July. Kampala had declared the outbreak over on 28 July counting from its own earlier discharge date, which is why the two declarations fell a month apart. PS Diana Atwine publicly called on countries to lift restrictions. NO ENTRY REQUIREMENT HAS CHANGED AS A RESULT. The US advisory remains LEVEL 4 (Do Not Travel), date issued 4 June 2026, verified directly on travel.state.gov on 27 Aug 2026 \u2014 and State's own advisory history attributes the 17 May 2026 escalation to the Bundibugyo outbreak in ITURI PROVINCE, DRC, not to Ugandan epidemiology. Quote the WHO certification; do not tell guests restrictions have lifted.", source:"Al Jazeera, 26 Aug 2026 (WHO/MoH joint press conference); travel.state.gov Uganda advisory read directly 27 Aug 2026", verified:true, flag:"action"}
    {rule:"US entry restrictions (CDC Title 42 / 42 CFR 71.40)", amount:"Rerouting through 4 designated US airports", who:"Travellers arriving in the US who were in Uganda or South Sudan in the past 21 days", effective:"Renewed 12 August 2026, 5:00pm EDT — in force to 4:59pm EDT Friday 11 September 2026", note:"CDC renewed the order on 12 Aug 2026 (signed PDF August-T42-Order_08.11.2026-signed.pdf). Uganda was NOT decoupled despite the 28 Jul Ebola-free declaration. US citizens and nationals from Uganda/South Sudan are not restricted but are rerouted to Dulles (IAD), Atlanta (ATL), Houston (IAH) or JFK for public health entry screening; US lawful permanent residents are named as restricted. Anyone in the DRC within 21 days \u2014 US citizens included \u2014 cannot board a US-bound flight. Note CDC\'s own legal-authorities page still listed the 13 Jul order as current when checked on 13 Aug. UPDATE 16 AUG: full text now readable — FR Doc 2026-16706, filed 14 Aug 08:45, publication date 17 Aug 2026, docket CDC-2026-0892. Continues the July order WITHOUT CHANGE and expires 4:59pm EDT Fri 11 Sep 2026. The operative determination reads Ebola is “confirmed currently present in DRC and RECENTLY present in Uganda” — past tense for Uganda — yet Uganda stays on the covered list on the stated ground of “continued overland travel from DRC”. The release condition is therefore DRC-side: the order cites contact tracing at ~78% against a 95% operational threshold| true outbreak size possibly two to four times greater than reported| and DRC at 4|318 confirmed / 2|011 deaths across 53 health zones as at 9 Aug (vs 1|873 / 672 across 41 zones at the 13 Jul order). CDC response is at Level 1| the highest in its Graduated Response Framework. A 15-DAY COMMENT PERIOD opens on publication 17 Aug and closes on or about 1 Sep| before the 11 Sep assessment: comments received to date were 3 (original+amended)| 5 (June)| and NONE on the July renewal. Uganda THN remains Level 2; Level 4 covers Ituri and North Kivu only.", source:"CDC returning-travellers page, updated 12 Aug 2026", verified:true, flag:"action"},
    {rule:"Canada entry \u2014 21-day arrival quarantine", amount:"21 days quarantine on arrival", who:"Anyone (citizens, PRs and foreign nationals) who was in Uganda or South Sudan in the past 21 days", effective:"In force since 20 Jul 2026 23:59 EDT; measures stated to run to 29 Aug 2026 23:59 EDT", note:"Materially harsher than the US rule and widely missed. Under the Quarantine Act, travellers from Uganda or South Sudan may enter Canada but must quarantine 21 days on arrival unless exempt. Anyone in the DRC within 21 days is prohibited from entering Canada or boarding a Canada-bound flight. Brief Canadian guests SEPARATELY from US guests \u2014 a single \'North America\' line in pre-arrival comms is wrong for both.", source:"travel.gc.ca health notice 550, modified 23 Jul 2026 / Public Health Agency of Canada", verified:true, flag:"action"},
    {rule:"Yellow fever certificate", amount:"Required", who:"All arrivals", effective:"Current", note:"Must be uploaded at visa application. A missing certificate stops the guest at immigration.", source:"Ministry of Health", verified:true},
    {rule:"National park entry waiver", amount:"US$0 — entry fees only", who:"All visitors, Ugandan and foreign, no nationality restriction", effective:"25, 26 & 27 September 2026", note:"Announced by State Minister for Tourism Susan Nsambu Nakawuki during a UWA tour of Murchison Falls. Covers park ENTRY fees. Whether game drives, boat cruises, guided walks and permits are included is NOT confirmed — verify with UWA before publishing a package price. Framed by officials as a counter to the 15 countries still holding advisories against Uganda.", source:"The Independent (UG) / Ministry of Tourism", verified:false, flag:"action"},
    {rule:"Tourism investment tax holiday", amount:"10-year income tax exemption", who:"High-end tourism projects: US$10m foreign / US$5m Ugandan investors", effective:"FY2026/27 budget", note:"Includes VAT waivers and duty-free import of hotel furniture, fittings and equipment. Announced by Finance Minister Henry Musasizi. Confirm qualifying criteria with the Uganda Investment Authority before modelling it into a deal.", source:"Daily Monitor / Nile Post / Uganda Investment Authority", verified:true, flag:"action"}
  ]},
  { country:"Tanzania", flag:"🇹🇿", items:[
    {rule:"EU Air Safety List \u2014 operating ban on Tanzanian-certified airlines", amount:"No fee \u2014 an operating ban", who:"Every airline certified in Tanzania (ATCL and all other TZ-registered operators); affects any itinerary that would place a guest on a Tanzanian-registered carrier into or within the EU", effective:"In force since 3 June 2025; RETAINED in the 48th update published 8 June 2026 (announced 9 June 2026)", note:"THE BAN IS ON THE REGULATOR, NOT THE FLEET. The Commission lists Tanzania among 16 states whose civil aviation authority it judges to provide inadequate safety oversight \u2014 not on aircraft airworthiness findings. Domestic and regional Tanzanian flying is unaffected. Kyrgyzstan was removed entirely in the same update, so the list is a two-way door. COMMERCIAL POINT: the Eurobarometer survey published alongside the update (fieldwork 24 Feb\u20131 Mar 2026) found only 8% of Europeans would still book a flight with a listed airline, 70% consider the list effective and 12% check it before flying. A widely circulated trade item (ATTA library, 15 Sep 2025, sourced to Tuko) claiming the ban had been lifted is FALSE \u2014 correct it wherever your agents repeat it. TCAA published a notice headlined \u0027TCAA and EU reaffirm commitment to strengthen aviation safety oversight\u0027 on 4 September 2026.", source:"European Commission DG MOVE, 48th update of the EU Air Safety List, 9 June 2026; TCAA newsroom, 4 September 2026", verified:true, flag:"action"},
    {rule:"Tourist visa", amount:"US$50 standard · US$100 US citizens", who:"US citizens receive multiple entry", effective:"Current", note:"Apply online ahead of travel.", source:"Tanzania Immigration", verified:true},
    {rule:"Mandatory electronic payments for licence", amount:"Compliant digital rail required (Lipa Namba / TANQR)", who:"Hotels, restaurants, safari & tourism operators", effective:"Effective 1 Jul 2026 — 6-month grace for existing businesses", note:"Under Electronic Transactions Act amendments and the Finance Act 2026, operators must offer a compliant digital-payment facility (mobile money, cards, POS, bank/internet transfer or govt e-payment) to obtain or renew a business licence. Existing operators have ~6 months (bite ~Jan 2027); after that, no compliant rail means no renewal.", source:"The Citizen / Daily News, effective 1 Jul 2026", verified:true, flag:"action"}
  ]},
  { country:"Zanzibar", flag:"🇹🇿", items:[
    {rule:"Mandatory inbound travel insurance", amount:"US$44 per adult", who:"Every foreign visitor", effective:"Since Oct 2024", note:"Bought from the Zanzibar government at visitzanzibar.go.tz — private policies do not substitute. Covers medical to US$50,000. PUT THIS IN YOUR PRE-ARRIVAL EMAIL: a guest discovering it at the airport is a bad review.", source:"Zanzibar Insurance Corporation", verified:true, flag:"action"},
    {rule:"Infrastructure tax (bed-night levy)", amount:"US$2–5 per person per night", who:"All in-house guests, by hotel star rating", effective:"Current", note:"Hotels must collect on behalf of the Zanzibar Revenue Board. Usually folded into the rate — decide deliberately whether you absorb or show it.", source:"Zanzibar Revenue Board", verified:true},
    {rule:"Card payment surcharge", amount:"3–5%", who:"Card transactions", effective:"Current", note:"Widely applied. Material on a long stay — flag it at booking, not checkout.", source:"Operator practice", verified:true},
    {rule:"Visa", amount:"US$50", who:"Most nationalities", effective:"Current", note:"Zanzibar follows Tanzania visa rules.", source:"Tanzania Immigration", verified:true},
    {rule:"Tour & excursion operations reserved for citizens", amount:"Local ownership required", who:"Tour, excursion & transfer operators on Zanzibar", effective:"Tourism Act No. 6 of 2009 — enforcement active Aug 2026", note:"Zanzibar Commission for Tourism + Immigration arrested three foreign nationals (incl. Kenyan Esther Mutheu Samuka) on 18 Aug 2026 for running excursion businesses reserved for Zanzibaris. Foreign-owned DMCs cannot directly run the ground product — excursions, spice tours, transfers — and must contract a LICENSED Zanzibari operator. Verify island partners licensing before selling packages.", source:"Zanzibar Commission for Tourism notice 17 Aug 2026 / Citizen Digital 21 Aug 2026", verified:true, flag:"action"}
  ]},
  { country:"Rwanda", flag:"🇷🇼", items:[
    {rule:"Gorilla permit", amount:"US$1,500", who:"Foreign non-resident", effective:"Current", note:"US$500 foreign resident · US$200 Rwandan & EAC citizens. Nearly 2× Uganda's US$800 — the pricing gap is a live competitive dynamic for the whole gorilla circuit.", source:"Rwanda Development Board", verified:true},
    {rule:"Tourist visa", amount:"~US$35", who:"Most nationalities", effective:"Verify before quoting", note:"Our most recent confirmation predates 2026 — confirm on the Irembo portal before publishing to clients.", source:"Irembo / RDB", verified:false},
    {rule:"Yellow fever certificate", amount:"Required", who:"All arrivals", effective:"Current", note:"Mandatory, uploaded at application.", source:"Ministry of Health", verified:true}
  ]},
  { country:"Regional", flag:"🌍", items:[
    {rule:"US Ebola entry restrictions & airport screening", amount:"No fee — screening and entry limits", who:"Anyone who has been in DRC, Uganda or South Sudan in the previous 21 days, regardless of nationality — INCLUDING US lawful permanent residents", effective:"Order signed 13 July 2026, in force to 4:59pm EDT Wednesday 12 August 2026", note:"CDC order under PHS Act ss.362/365, published at 91 FR 43636 on 16 July 2026, docket CDC-2026-0892. THE GREEN CARD EXEMPTION IS GONE: 42 CFR 71.40(f) was amended on 27 May 2026 (91 FR 31362) and the order applies expressly to lawful permanent residents. Exempt: US citizens and nationals, US military and government personnel on orders, and case-by-case CBP/CDC exceptions. DHS separately funnels affected flights to Washington Dulles (IAD) under 91 FR 29896, 21 May 2026. The order names Nairobi JKIA, Addis Ababa, Doha, Dubai, Brussels and Istanbul as transit corridors of concern — Kenya itself is NOT restricted. PUBLIC COMMENT CLOSES 31 JULY 2026 at regulations.gov under docket CDC-2026-0892; CDC has already refused, in writing, a request to assess Uganda independently of DRC. Next decision point 12 August. UPDATE 29 JUL: Uganda\'s Ministry of Health declared the outbreak OVER on 28 July 2026 — thirty days before the diarised ~27 August all-clear — so the 12 August renewal now falls AFTER a formal end-of-outbreak declaration, not before it. As at 08:00 EAT 29 July we can find no WHO statement endorsing the declaration and no change to the CDC order or the US Level 4 advisory. Sell \'outbreak over\', not \'restrictions lifted\'. UPDATE 5 AUG: WHO DON614 (1 Aug| revised 3 Aug) reports epidemiological week 30 as the outbreak\'s worst week yet (567 cases| 296 deaths) and confirms it is now the largest Ebola outbreak on record in DRC (3|605 confirmed| 1|587 deaths| 44% CFR). A WHO IHR Emergency Committee meets 18 August — six days after the 12 Aug US renewal point. UPDATE 20 AUG: the committee met on 18 Aug (its second meeting). WHO AFRO 18 Aug report: 5|021 confirmed / 2|378 deaths across 55 health zones in six provinces (Ituri 4|257/1|878; North Kivu 607/428 across 12 of 34 zones; South Kivu first 3 cases/1 death) — up from 4|318/2|011 on 9 Aug, and now creeping into provinces bordering Uganda and Rwanda. Advisory levels and entry orders unchanged; next US assessment 11 Sep.", source:"CDC Order 13 Jul 2026 / 91 FR 43636, 16 Jul 2026", verified:true, flag:"action"},
    {rule:"East Africa Tourist Visa (EATV)", amount:"US$100", who:"Kenya + Uganda + Rwanda", effective:"Current", note:"90-day multiple entry, free movement between the three. Apply through your FIRST country of entry. Materially cheaper than three separate visas — sell multi-country itineraries on it.", source:"EAC partner states", verified:true, flag:"action"}
  ]}
 ]
};
